// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package generated

type SearchResult interface {
	IsSearchResult()
}

type Article struct {
	ID     string  `json:"id"`
	Title  string  `json:"title"`
	Author *Author `json:"author,omitempty"`
}

func (Article) IsSearchResult() {}

type Author struct {
	Name string  `json:"name"`
	Bio  *string `json:"bio,omitempty"`
}

type Query struct {
}

type Video struct {
	ID       string `json:"id"`
	Duration int    `json:"duration"`
}

func (Video) IsSearchResult() {}
