// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package domain

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/99designs/gqlgen/graphql"
)

type FilterInput struct {
	Field string `json:"field"`
	Value string `json:"value"`
}

type PageInput struct {
	Size int `json:"size"`
}

type SearchInput struct {
	Keyword      string                              `json:"keyword"`
	Status       Status                              `json:"status"`
	Page         graphql.Omittable[*PageInput]       `json:"page,omitempty,omitzero"`
	CreatedAfter graphql.Omittable[*time.Time]       `json:"createdAfter,omitempty,omitzero"`
	Meta         graphql.Omittable[*string]          `json:"meta,omitempty,omitzero"`
	Filters      graphql.Omittable[[][]*FilterInput] `json:"filters,omitempty,omitzero"`
}

type Status string

const (
	StatusActive   Status = "ACTIVE"
	StatusInactive Status = "INACTIVE"
)

var AllStatus = []Status{
	StatusActive,
	StatusInactive,
}

func (e Status) IsValid() bool {
	switch e {
	case StatusActive, StatusInactive:
		return true
	}
	return false
}

func (e Status) String() string {
	return string(e)
}

func (e *Status) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Status(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Status", str)
	}
	return nil
}

func (e Status) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Status) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Status) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
