package clientgenv2

import (
	"bytes"
	_ "embed" // used to load template file
	"fmt"
	"go/types"
	"strings"

	"github.com/99designs/gqlgen/codegen/config"
	"github.com/99designs/gqlgen/codegen/templates"

	gqlgencConfig "github.com/gqlgo/gqlgenc/config"
)

//go:embed template.gotpl
var template string

func RenderTemplate(cfg *config.Config, fragments []*Fragment, operations []*Operation, operationResponses []*OperationResponse, structSources []*StructSource, generateCfg *gqlgencConfig.GenerateConfig, client config.PackageConfig) error {
	genGettersGenerator := &GenGettersGenerator{
		ClientPackageName: client.Package,
	}

	err := templates.Render(templates.Options{
		PackageName: client.Package,
		Filename:    client.Filename,
		Template:    template,
		Data: map[string]any{
			"Fragment":            fragments,
			"Operation":           operations,
			"OperationResponse":   operationResponses,
			"GenerateClient":      generateCfg.ShouldGenerateClient(),
			"StructSources":       structSources,
			"ClientInterfaceName": generateCfg.GetClientInterfaceName(),
		},
		Packages:   cfg.Packages,
		PackageDoc: "// Code generated by github.com/gqlgo/gqlgenc, DO NOT EDIT.\n",
		Funcs: map[string]any{
			"genGetters":             genGettersGenerator.GenFunc(),
			"genConversionGetters": genGettersGenerator.ConversionGettersFunc(fragments),
		},
	})
	if err != nil {
		return fmt.Errorf("%s generating failed: %w", client.Filename, err)
	}

	return nil
}

type GenGettersGenerator struct {
	ClientPackageName string
}

func (g *GenGettersGenerator) GenFunc() func(name string, p types.Type) string {
	// This method returns a string of getters for a struct.
	// The idea is to be able to chain calls safely without having to check for nil.
	// To make this work we need to return a pointer to the struct if the field is a struct.
	return func(name string, p types.Type) string {
		var it *types.Struct

		it, ok := p.(*types.Struct)
		if !ok {
			return ""
		}

		var buf bytes.Buffer

		for i := range it.NumFields() {
			field := it.Field(i)

			returns := g.returnTypeName(field.Type(), false)

			buf.WriteString("func (t *" + name + ") Get" + field.Name() + "() " + returns + "{\n")
			buf.WriteString("if t == nil {\n t = &" + name + "{}\n}\n")

			pointerOrNot := ""
			if _, ok := field.Type().(*types.Named); ok {
				pointerOrNot = "&"
			}

			buf.WriteString("return " + pointerOrNot + "t." + field.Name() + "\n}\n")
		}

		return buf.String()
	}
}

func (g *GenGettersGenerator) returnTypeName(t types.Type, nested bool) string {
	switch it := t.(type) {
	case *types.Basic:
		return it.String()
	case *types.Pointer:
		return "*" + g.returnTypeName(it.Elem(), true)
	case *types.Slice:
		return "[]" + g.returnTypeName(it.Elem(), true)
	case *types.Named:
		s := strings.Split(it.String(), ".")
		name := s[len(s)-1]

		isImported := it.Obj().Parent() != nil && it.Obj().Pkg().Name() != g.ClientPackageName
		if isImported {
			name = namedTypeString(it)
		}

		if nested {
			return name
		}

		return "*" + name
	case *types.Interface:
		return "any"
	case *types.Map:
		return "map[" + g.returnTypeName(it.Key(), true) + "]" + g.returnTypeName(it.Elem(), true)
	case *types.Alias:
		return g.returnTypeName(it.Underlying(), nested)
	default:
		return fmt.Sprintf("%T----", it)
	}
}

// ConversionGettersFunc returns a template function that generates conversion getters
// for spread fragments. Each getter constructs the original fragment type from the
// flattened parent struct's fields.
func (g *GenGettersGenerator) ConversionGettersFunc(allFragments []*Fragment) func(ownerName string, spreads []*SpreadFragmentInfo) string {
	// Build a map of fragment name -> resolved Fragment for type lookup.
	fragmentMap := make(map[string]*Fragment, len(allFragments))
	for _, f := range allFragments {
		fragmentMap[f.Name] = f
	}

	return func(ownerName string, spreads []*SpreadFragmentInfo) string {
		if len(spreads) == 0 {
			return ""
		}

		var buf bytes.Buffer

		for _, spread := range spreads {
			targetFragment, ok := fragmentMap[spread.Name]
			if !ok {
				continue
			}

			targetStruct, ok := targetFragment.Type.(*types.Struct)
			if !ok {
				continue
			}

			targetTypeName := g.typeName(spread.Type)

			buf.WriteString("func (t *" + ownerName + ") Get" + targetTypeName + "() *" + targetTypeName + " {\n")
			buf.WriteString("if t == nil {\n t = &" + ownerName + "{}\n}\n")
			buf.WriteString("return &" + targetTypeName + "{\n")
			g.writeStructLiteral(&buf, targetStruct, "t")
			buf.WriteString("}\n}\n")
		}

		return buf.String()
	}
}

// writeStructLiteral writes field assignments for a struct literal, recursively
// handling nested structs with different types.
func (g *GenGettersGenerator) writeStructLiteral(buf *bytes.Buffer, targetStruct *types.Struct, sourceExpr string) {
	for i := range targetStruct.NumFields() {
		field := targetStruct.Field(i)
		fieldName := field.Name()

		targetFieldStruct := underlyingStruct(field.Type())
		if targetFieldStruct != nil {
			// Nested struct field — check if types differ and need recursive construction.
			buf.WriteString(fieldName + ": " + g.typeName(field.Type()) + "{\n")
			g.writeStructLiteral(buf, targetFieldStruct, sourceExpr+"."+fieldName)
			buf.WriteString("},\n")
		} else {
			buf.WriteString(fieldName + ": " + sourceExpr + "." + fieldName + ",\n")
		}
	}
}

// typeName extracts the short type name from a types.Type.
func (g *GenGettersGenerator) typeName(t types.Type) string {
	switch it := t.(type) {
	case *types.Named:
		s := strings.Split(it.String(), ".")
		return s[len(s)-1]
	case *types.Pointer:
		return g.typeName(it.Elem())
	default:
		return t.String()
	}
}

// underlyingStruct returns the *types.Struct if t is a named struct type, nil otherwise.
func underlyingStruct(t types.Type) *types.Struct {
	// Unwrap pointer
	if ptr, ok := t.(*types.Pointer); ok {
		t = ptr.Elem()
	}

	named, ok := t.(*types.Named)
	if !ok {
		return nil
	}

	st, ok := named.Underlying().(*types.Struct)
	if !ok {
		return nil
	}

	return st
}

func namedTypeString(named *types.Named) string {
	// オブジェクトからパッケージ情報を取得
	pkg := named.Obj().Pkg()

	// パッケージ情報がない場合、型名のみを返す
	if pkg == nil {
		return named.Obj().Name()
	}

	// パッケージ名と型名を結合して返す
	return fmt.Sprintf("%s.%s", pkg.Name(), named.Obj().Name())
}
