// Code generated by github.com/gqlgo/gqlgenc, DO NOT EDIT.

package generated

import (
	"context"

	"github.com/gqlgo/gqlgenc/clientv2"
)

type Client struct {
	Client *clientv2.Client
}

func NewClient(cli clientv2.HttpClient, baseURL string, options *clientv2.Options, interceptors ...clientv2.RequestInterceptor) *Client {
	return &Client{Client: clientv2.NewClient(cli, baseURL, options, interceptors...)}
}

type Search_Search_Article struct {
	ID    string "json:\"id\" graphql:\"id\""
	Title string "json:\"title\" graphql:\"title\""
}

func (t *Search_Search_Article) GetID() string {
	if t == nil {
		t = &Search_Search_Article{}
	}
	return t.ID
}
func (t *Search_Search_Article) GetTitle() string {
	if t == nil {
		t = &Search_Search_Article{}
	}
	return t.Title
}

type Search_Search_Video struct {
	ID       string "json:\"id\" graphql:\"id\""
	Duration int    "json:\"duration\" graphql:\"duration\""
}

func (t *Search_Search_Video) GetID() string {
	if t == nil {
		t = &Search_Search_Video{}
	}
	return t.ID
}
func (t *Search_Search_Video) GetDuration() int {
	if t == nil {
		t = &Search_Search_Video{}
	}
	return t.Duration
}

type Search_Search struct {
	Article  Search_Search_Article "graphql:\"... on Article\""
	Video    Search_Search_Video   "graphql:\"... on Video\""
	Typename *string               "json:\"__typename,omitempty\" graphql:\"__typename\""
}

func (t *Search_Search) GetArticle() *Search_Search_Article {
	if t == nil {
		t = &Search_Search{}
	}
	return &t.Article
}
func (t *Search_Search) GetVideo() *Search_Search_Video {
	if t == nil {
		t = &Search_Search{}
	}
	return &t.Video
}
func (t *Search_Search) GetTypename() *string {
	if t == nil {
		t = &Search_Search{}
	}
	return t.Typename
}

type Search struct {
	Search Search_Search "json:\"search\" graphql:\"search\""
}

func (t *Search) GetSearch() *Search_Search {
	if t == nil {
		t = &Search{}
	}
	return &t.Search
}

const SearchDocument = `query Search ($query: String!) {
	search(query: $query) {
		__typename
		... on Article {
			id
			title
		}
		... on Video {
			id
			duration
		}
	}
}
`

func (c *Client) Search(ctx context.Context, query string, interceptors ...clientv2.RequestInterceptor) (*Search, error) {
	vars := map[string]any{
		"query": query,
	}

	var res Search
	if err := c.Client.Post(ctx, "Search", SearchDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

var DocumentOperationNames = map[string]string{
	SearchDocument: "Search",
}
