// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package generated

type SearchResult interface {
	IsSearchResult()
}

type Article struct {
	ID    string `json:"id"`
	Title string `json:"title"`
}

func (Article) IsSearchResult() {}

type Query struct {
}

type Video struct {
	ID       string `json:"id"`
	Duration int    `json:"duration"`
}

func (Video) IsSearchResult() {}
