// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package generated

type Node interface {
	IsNode()
	GetID() string
}

type SearchResult interface {
	IsSearchResult()
}

type Article struct {
	ID    string `json:"id"`
	Title string `json:"title"`
}

func (Article) IsNode()            {}
func (this Article) GetID() string { return this.ID }

func (Article) IsSearchResult() {}

type Profile struct {
	Name string  `json:"name"`
	Bio  *string `json:"bio,omitempty"`
}

type Query struct {
}

type User struct {
	ID      string   `json:"id"`
	Name    string   `json:"name"`
	Profile *Profile `json:"profile,omitempty"`
}

func (User) IsNode()            {}
func (this User) GetID() string { return this.ID }

type Video struct {
	ID       string `json:"id"`
	Duration int    `json:"duration"`
}

func (Video) IsNode()            {}
func (this Video) GetID() string { return this.ID }

func (Video) IsSearchResult() {}
