// Code generated by github.com/gqlgo/gqlgenc, DO NOT EDIT.

package generated

type Hello struct {
	Hello string "json:\"hello\" graphql:\"hello\""
}

func (t *Hello) GetHello() string {
	if t == nil {
		t = &Hello{}
	}
	return t.Hello
}

const HelloDocument = `query Hello {
	hello
}
`

var DocumentOperationNames = map[string]string{
	HelloDocument: "Hello",
}
