// Code generated by github.com/gqlgo/gqlgenc, DO NOT EDIT.

package generated

import (
	"context"

	"github.com/gqlgo/gqlgenc/clientv2"
)

type Client struct {
	Client *clientv2.Client
}

func NewClient(cli clientv2.HttpClient, baseURL string, options *clientv2.Options, interceptors ...clientv2.RequestInterceptor) *Client {
	return &Client{Client: clientv2.NewClient(cli, baseURL, options, interceptors...)}
}

type GetUser_User struct {
	Age   *int    "json:\"age,omitzero\" graphql:\"age\""
	Bio   *string "json:\"bio,omitzero\" graphql:\"bio\""
	Email *string "json:\"email,omitzero\" graphql:\"email\""
	ID    string  "json:\"id\" graphql:\"id\""
	Name  string  "json:\"name\" graphql:\"name\""
}

func (t *GetUser_User) GetAge() *int {
	if t == nil {
		t = &GetUser_User{}
	}
	return t.Age
}
func (t *GetUser_User) GetBio() *string {
	if t == nil {
		t = &GetUser_User{}
	}
	return t.Bio
}
func (t *GetUser_User) GetEmail() *string {
	if t == nil {
		t = &GetUser_User{}
	}
	return t.Email
}
func (t *GetUser_User) GetID() string {
	if t == nil {
		t = &GetUser_User{}
	}
	return t.ID
}
func (t *GetUser_User) GetName() string {
	if t == nil {
		t = &GetUser_User{}
	}
	return t.Name
}

type GetUserNullable_User struct {
	Age   *int    "json:\"age,omitzero\" graphql:\"age\""
	Bio   *string "json:\"bio,omitzero\" graphql:\"bio\""
	Email *string "json:\"email,omitzero\" graphql:\"email\""
	ID    string  "json:\"id\" graphql:\"id\""
	Name  string  "json:\"name\" graphql:\"name\""
}

func (t *GetUserNullable_User) GetAge() *int {
	if t == nil {
		t = &GetUserNullable_User{}
	}
	return t.Age
}
func (t *GetUserNullable_User) GetBio() *string {
	if t == nil {
		t = &GetUserNullable_User{}
	}
	return t.Bio
}
func (t *GetUserNullable_User) GetEmail() *string {
	if t == nil {
		t = &GetUserNullable_User{}
	}
	return t.Email
}
func (t *GetUserNullable_User) GetID() string {
	if t == nil {
		t = &GetUserNullable_User{}
	}
	return t.ID
}
func (t *GetUserNullable_User) GetName() string {
	if t == nil {
		t = &GetUserNullable_User{}
	}
	return t.Name
}

type GetUser struct {
	User GetUser_User "json:\"user\" graphql:\"user\""
}

func (t *GetUser) GetUser() *GetUser_User {
	if t == nil {
		t = &GetUser{}
	}
	return &t.User
}

type GetUserNullable struct {
	User GetUserNullable_User "json:\"user\" graphql:\"user\""
}

func (t *GetUserNullable) GetUser() *GetUserNullable_User {
	if t == nil {
		t = &GetUserNullable{}
	}
	return &t.User
}

const GetUserDocument = `query GetUser ($id: ID!) {
	user(id: $id) {
		id @dummy_custom(value: "user-123")
		name @dummy_custom(value: "Alice")
		email @dummy_custom(value: "alice@example.com")
		age @dummy_int(min: 30, max: 30)
		bio @dummy_custom(value: "Hello world")
	}
}
`

func (c *Client) GetUser(ctx context.Context, id string, interceptors ...clientv2.RequestInterceptor) (*GetUser, error) {
	vars := map[string]any{
		"id": id,
	}

	var res GetUser
	if err := c.Client.Post(ctx, "GetUser", GetUserDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const GetUserNullableDocument = `query GetUserNullable ($id: ID!) {
	user(id: $id) {
		id @dummy_custom(value: "user-456")
		name @dummy_custom(value: "Bob")
		email
		age
		bio
	}
}
`

func (c *Client) GetUserNullable(ctx context.Context, id string, interceptors ...clientv2.RequestInterceptor) (*GetUserNullable, error) {
	vars := map[string]any{
		"id": id,
	}

	var res GetUserNullable
	if err := c.Client.Post(ctx, "GetUserNullable", GetUserNullableDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

var DocumentOperationNames = map[string]string{
	GetUserDocument:         "GetUser",
	GetUserNullableDocument: "GetUserNullable",
}
