// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package generated

type Query struct {
}

type User struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Email *string `json:"email,omitzero"`
	Age   *int    `json:"age,omitzero"`
	Bio   *string `json:"bio,omitzero"`
}
