package querygen

import (
	_ "embed" // used to load template file
	"fmt"
	"go/types"

	"github.com/99designs/gqlgen/codegen/templates"

	"github.com/Yamashou/gqlgenc/v3/codegen"
	"github.com/Yamashou/gqlgenc/v3/config"
	"github.com/Yamashou/gqlgenc/v3/plugins/querygen/generator"
)

//go:embed template.tmpl
var template string

func RenderTemplate(cfg *config.Config, operations []*codegen.Operation, goTypes []types.Type) error {
	// Create code generator with the analyzed types
	codeGen := generator.NewCodeGenerator(goTypes)

	if err := templates.Render(templates.Options{
		PackageName:     cfg.GQLGencConfig.QueryGen.Package,
		Template:        template,
		TemplateFS:      nil,
		Filename:        cfg.GQLGencConfig.QueryGen.Filename,
		RegionTags:      false,
		GeneratedHeader: false,
		PackageDoc:      "// Code generated by github.com/Yamashou/gqlgenc, DO NOT EDIT.\n",
		FileNotice:      "",
		Data: map[string]any{
			"GoTypes":    goTypes,
			"Operations": operations,
		},
		Funcs: map[string]any{
			"genCode": func(t types.Type) string {
				code, err := codeGen.Generate(t)
				if err != nil {
					panic(fmt.Errorf("failed to generate code for type %v: %w", t, err))
				}
				return code
			},
			"needsJSONImport": func() bool {
				return codeGen.NeedsJSONImport(goTypes)
			},
		},
		Packages: cfg.GQLGenConfig.Packages,
	}); err != nil {
		return fmt.Errorf("%s generating failed: %w", cfg.GQLGencConfig.QueryGen.Filename, err)
	}

	return nil
}
