package querygen

import (
	_ "embed" // used to load template file
	"fmt"
	"go/types"

	"github.com/99designs/gqlgen/codegen/templates"

	"github.com/Yamashou/gqlgenc/v3/codegen"
	"github.com/Yamashou/gqlgenc/v3/config"
)

//go:embed template.tmpl
var template string

// RenderTemplate は埋め込みテンプレートをレンダリングしてクエリ型ファイルを生成する。
//
// この関数は以下の処理を行う:
//  1. 型生成ロジックを扱う CodeGenerator を作成
//  2. オペレーションと型データでテンプレートをレンダリング
//  3. テンプレート関数 "genCode" と "needsJSONImport" を提供
//  4. 生成されたコードを設定されたファイル名に書き込み
//
// パラメータ:
//   - cfg: 出力場所とパッケージ名を指定する gqlgenc 設定
//   - operations: 生成ファイルに含める GraphQL オペレーション
//   - goTypes: コード生成対象の Go 型（オペレーションレスポンス型）
//
// テンプレートのレンダリングが失敗した場合はエラーを返す。
func RenderTemplate(cfg *config.Config, operations []*codegen.Operation, goTypes []types.Type) error {
	// 解析済みの型で CodeGenerator を作成
	codeGen := NewCodeGenerator(goTypes)

	if err := templates.Render(templates.Options{
		PackageName:     cfg.GQLGencConfig.QueryGen.Package,
		Template:        template,
		TemplateFS:      nil,
		Filename:        cfg.GQLGencConfig.QueryGen.Filename,
		RegionTags:      false,
		GeneratedHeader: false,
		PackageDoc:      "// Code generated by github.com/Yamashou/gqlgenc, DO NOT EDIT.\n",
		FileNotice:      "",
		Data: map[string]any{
			"GoTypes":    goTypes,
			"Operations": operations,
		},
		Funcs: map[string]any{
			"genCode": func(t types.Type) string {
				code, err := codeGen.Generate(t)
				if err != nil {
					panic(fmt.Errorf("failed to generate code for type %v: %w", t, err))
				}
				return code
			},
			"needsJSONImport": func() bool {
				return codeGen.NeedsJSONImport(goTypes)
			},
		},
		Packages: cfg.GQLGenConfig.Packages,
	}); err != nil {
		return fmt.Errorf("%s generating failed: %w", cfg.GQLGencConfig.QueryGen.Filename, err)
	}

	return nil
}
