// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package domain

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type CellKind string

const (
	CellKindText   CellKind = "TEXT"
	CellKindNumber CellKind = "NUMBER"
)

var AllCellKind = []CellKind{
	CellKindText,
	CellKindNumber,
}

func (e CellKind) IsValid() bool {
	switch e {
	case CellKindText, CellKindNumber:
		return true
	}
	return false
}

func (e CellKind) String() string {
	return string(e)
}

func (e *CellKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CellKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CellKind", str)
	}
	return nil
}

func (e CellKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CellKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CellKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
