// Code generated by github.com/gqlgo/gqlgenc, DO NOT EDIT.

package generated

import (
	"context"

	"github.com/gqlgo/gqlgenc/clientv2"
)

type Client struct {
	Client *clientv2.Client
}

func NewClient(cli clientv2.HttpClient, baseURL string, options *clientv2.Options, interceptors ...clientv2.RequestInterceptor) *Client {
	return &Client{Client: clientv2.NewClient(cli, baseURL, options, interceptors...)}
}

type GetThing_GetThing struct {
	Flag *bool  "json:\"flag,omitempty\" graphql:\"flag\""
	ID   string "json:\"id\" graphql:\"id\""
}

func (t *GetThing_GetThing) GetFlag() *bool {
	if t == nil {
		t = &GetThing_GetThing{}
	}
	return t.Flag
}
func (t *GetThing_GetThing) GetID() string {
	if t == nil {
		t = &GetThing_GetThing{}
	}
	return t.ID
}

type GetThing struct {
	GetThing *GetThing_GetThing "json:\"getThing,omitempty\" graphql:\"getThing\""
}

func (t *GetThing) GetGetThing() *GetThing_GetThing {
	if t == nil {
		t = &GetThing{}
	}
	return t.GetThing
}

const GetThingDocument = `query GetThing {
	getThing {
		id
		flag
	}
}
`

func (c *Client) GetThing(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*GetThing, error) {
	vars := map[string]any{}

	var res GetThing
	if err := c.Client.Post(ctx, "GetThing", GetThingDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

var DocumentOperationNames = map[string]string{
	GetThingDocument: "GetThing",
}
