// Code generated by github.com/Yamashou/gqlgenc, DO NOT EDIT.

package domain

import (
	"encoding/json/jsontext"
	json "encoding/json/v2"
)

type Search struct {
	Node        *Search_Node          "json:\"node\""
	SearchInput Search_SearchInput    "json:\"searchInput\""
	SearchNodes []*Search_SearchNodes "json:\"searchNodes\""
}

type Search_Node struct {
	Post *struct {
		Title string "json:\"title\""
	} "json:\"-\""
	User *struct {
		Name string "json:\"name\""
	} "json:\"-\""
	Typename string "json:\"__typename\""
	ID       string "json:\"id\""
}

func (t *Search_Node) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	data, err := dec.ReadValue()
	if err != nil {
		return err
	}
	type plain Search_Node
	if err := json.Unmarshal(data, (*plain)(t)); err != nil {
		return err
	}
	switch t.Typename {
	case "Post":
		if err := json.Unmarshal(data, &t.Post); err != nil {
			return err
		}
	case "User":
		if err := json.Unmarshal(data, &t.User); err != nil {
			return err
		}
	}
	return nil
}

type Search_SearchInput struct {
	Status Status "json:\"status\""
	Total  int    "json:\"total\""
}

type Search_SearchNodes struct {
	Post *struct {
		ID    string "json:\"id\""
		Title string "json:\"title\""
	} "json:\"-\""
	User *struct {
		ID   string   "json:\"id\""
		Kind NodeKind "json:\"kind\""
		Name string   "json:\"name\""
	} "json:\"-\""
	Typename string "json:\"__typename\""
}

func (t *Search_SearchNodes) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	data, err := dec.ReadValue()
	if err != nil {
		return err
	}
	type plain Search_SearchNodes
	if err := json.Unmarshal(data, (*plain)(t)); err != nil {
		return err
	}
	switch t.Typename {
	case "Post":
		if err := json.Unmarshal(data, &t.Post); err != nil {
			return err
		}
	case "User":
		if err := json.Unmarshal(data, &t.User); err != nil {
			return err
		}
	}
	return nil
}

const SearchDocument = `query Search($input: SearchInput!, $filter: SearchFilter!) { searchInput(input: $input) { total status } searchNodes(filter: $filter) { __typename ... on User { id name kind } ... on Post { id title } } node(id: "1") { __typename id ... on User { name } ... on Post { title } } }`
