// Code generated by github.com/gqlgo/gqlgenc, DO NOT EDIT.

package generated

import (
	"context"

	"github.com/gqlgo/gqlgenc/clientv2"
)

type Client struct {
	Client *clientv2.Client
}

func NewClient(cli clientv2.HttpClient, baseURL string, options *clientv2.Options, interceptors ...clientv2.RequestInterceptor) *Client {
	return &Client{Client: clientv2.NewClient(cli, baseURL, options, interceptors...)}
}

type ArticleFields struct {
	ID    string "json:\"id\" graphql:\"id\""
	Title string "json:\"title\" graphql:\"title\""
}

func (t *ArticleFields) GetID() string {
	if t == nil {
		t = &ArticleFields{}
	}
	return t.ID
}
func (t *ArticleFields) GetTitle() string {
	if t == nil {
		t = &ArticleFields{}
	}
	return t.Title
}

type VideoFields struct {
	Duration int "json:\"duration\" graphql:\"duration\""
}

func (t *VideoFields) GetDuration() int {
	if t == nil {
		t = &VideoFields{}
	}
	return t.Duration
}

type NodeFields struct {
	ID string "json:\"id\" graphql:\"id\""
}

func (t *NodeFields) GetID() string {
	if t == nil {
		t = &NodeFields{}
	}
	return t.ID
}

type UserFragment struct {
	ID      string                "json:\"id\" graphql:\"id\""
	Profile *UserFragment_Profile "json:\"profile,omitempty\" graphql:\"profile\""
}

func (t *UserFragment) GetID() string {
	if t == nil {
		t = &UserFragment{}
	}
	return t.ID
}
func (t *UserFragment) GetProfile() *UserFragment_Profile {
	if t == nil {
		t = &UserFragment{}
	}
	return t.Profile
}

type UserFragment_Profile struct {
	Bio *string "json:\"bio,omitempty\" graphql:\"bio\""
}

func (t *UserFragment_Profile) GetBio() *string {
	if t == nil {
		t = &UserFragment_Profile{}
	}
	return t.Bio
}

type Search_Search_Video struct {
	ID       string "json:\"id\" graphql:\"id\""
	Duration int    "json:\"duration\" graphql:\"duration\""
}

func (t *Search_Search_Video) GetID() string {
	if t == nil {
		t = &Search_Search_Video{}
	}
	return t.ID
}
func (t *Search_Search_Video) GetDuration() int {
	if t == nil {
		t = &Search_Search_Video{}
	}
	return t.Duration
}

type Search_Search struct {
	Article  *ArticleFields       "graphql:\"... on Article\""
	Video    *Search_Search_Video "graphql:\"... on Video\""
	Typename *string              "json:\"__typename,omitempty\" graphql:\"__typename\""
}

func (t *Search_Search) GetArticle() *ArticleFields {
	if t == nil {
		t = &Search_Search{}
	}
	return t.Article
}
func (t *Search_Search) GetVideo() *Search_Search_Video {
	if t == nil {
		t = &Search_Search{}
	}
	return t.Video
}
func (t *Search_Search) GetTypename() *string {
	if t == nil {
		t = &Search_Search{}
	}
	return t.Typename
}

type GetNodes_A_Article struct {
	Title string "json:\"title\" graphql:\"title\""
}

func (t *GetNodes_A_Article) GetTitle() string {
	if t == nil {
		t = &GetNodes_A_Article{}
	}
	return t.Title
}

type GetNodes_A struct {
	Article  *GetNodes_A_Article "graphql:\"... on Article\""
	Typename *string             "json:\"__typename,omitempty\" graphql:\"__typename\""
	ID       string              "json:\"id\" graphql:\"id\""
}

func (t *GetNodes_A) GetArticle() *GetNodes_A_Article {
	if t == nil {
		t = &GetNodes_A{}
	}
	return t.Article
}
func (t *GetNodes_A) GetTypename() *string {
	if t == nil {
		t = &GetNodes_A{}
	}
	return t.Typename
}
func (t *GetNodes_A) GetID() string {
	if t == nil {
		t = &GetNodes_A{}
	}
	return t.ID
}

type GetNodes_B struct {
	Video    *VideoFields "graphql:\"... on Video\""
	Typename *string      "json:\"__typename,omitempty\" graphql:\"__typename\""
	ID       string       "json:\"id\" graphql:\"id\""
}

func (t *GetNodes_B) GetVideo() *VideoFields {
	if t == nil {
		t = &GetNodes_B{}
	}
	return t.Video
}
func (t *GetNodes_B) GetTypename() *string {
	if t == nil {
		t = &GetNodes_B{}
	}
	return t.Typename
}
func (t *GetNodes_B) GetID() string {
	if t == nil {
		t = &GetNodes_B{}
	}
	return t.ID
}

type GetUser_User_Profile struct {
	Bio  *string "json:\"bio,omitempty\" graphql:\"bio\""
	Name string  "json:\"name\" graphql:\"name\""
}

func (t *GetUser_User_Profile) GetBio() *string {
	if t == nil {
		t = &GetUser_User_Profile{}
	}
	return t.Bio
}
func (t *GetUser_User_Profile) GetName() string {
	if t == nil {
		t = &GetUser_User_Profile{}
	}
	return t.Name
}

type GetUser_User struct {
	ID      string                "json:\"id\" graphql:\"id\""
	Profile *GetUser_User_Profile "json:\"profile,omitempty\" graphql:\"profile\""
}

func (t *GetUser_User) GetID() string {
	if t == nil {
		t = &GetUser_User{}
	}
	return t.ID
}
func (t *GetUser_User) GetProfile() *GetUser_User_Profile {
	if t == nil {
		t = &GetUser_User{}
	}
	return t.Profile
}

type Search struct {
	Search []*Search_Search "json:\"search\" graphql:\"search\""
}

func (t *Search) GetSearch() []*Search_Search {
	if t == nil {
		t = &Search{}
	}
	return t.Search
}

type GetNodes struct {
	A *GetNodes_A "json:\"a,omitempty\" graphql:\"a\""
	B *GetNodes_B "json:\"b,omitempty\" graphql:\"b\""
}

func (t *GetNodes) GetA() *GetNodes_A {
	if t == nil {
		t = &GetNodes{}
	}
	return t.A
}
func (t *GetNodes) GetB() *GetNodes_B {
	if t == nil {
		t = &GetNodes{}
	}
	return t.B
}

type GetUser struct {
	User *GetUser_User "json:\"user,omitempty\" graphql:\"user\""
}

func (t *GetUser) GetUser() *GetUser_User {
	if t == nil {
		t = &GetUser{}
	}
	return t.User
}

const SearchDocument = `query Search ($query: String!) {
	search(query: $query) {
		__typename
		... on Article {
			... ArticleFields
		}
		... on Video {
			id
			... VideoFields
		}
	}
}
fragment ArticleFields on Article {
	id
	title
}
fragment VideoFields on Video {
	duration
}
`

func (c *Client) Search(ctx context.Context, query string, interceptors ...clientv2.RequestInterceptor) (*Search, error) {
	vars := map[string]any{
		"query": query,
	}

	var res Search
	if err := c.Client.Post(ctx, "Search", SearchDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const GetNodesDocument = `query GetNodes {
	a: node(id: "1") {
		__typename
		... NodeFields
		... on Article {
			title
		}
	}
	b: node(id: "2") {
		__typename
		id
		... on Video {
			... VideoFields
		}
	}
}
fragment NodeFields on Node {
	id
}
fragment VideoFields on Video {
	duration
}
`

func (c *Client) GetNodes(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*GetNodes, error) {
	vars := map[string]any{}

	var res GetNodes
	if err := c.Client.Post(ctx, "GetNodes", GetNodesDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const GetUserDocument = `query GetUser {
	user {
		... UserFragment
		id
		profile {
			name
		}
	}
}
fragment UserFragment on User {
	id
	profile {
		bio
	}
}
`

func (c *Client) GetUser(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*GetUser, error) {
	vars := map[string]any{}

	var res GetUser
	if err := c.Client.Post(ctx, "GetUser", GetUserDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

var DocumentOperationNames = map[string]string{
	SearchDocument:   "Search",
	GetNodesDocument: "GetNodes",
	GetUserDocument:  "GetUser",
}
