// Code generated by github.com/Yamashou/gqlgenc, DO NOT EDIT.

package query

import (
	"github.com/Yamashou/gqlgenc/v3/client"
	"github.com/Yamashou/gqlgenc/v3/testdata/integration/basic/domain"
)

type UpdateUserVars struct {
	Input domain.UpdateUserInput `json:"input"`
}

var UpdateUserOp = client.Operation[client.Mutation, UpdateUserVars, domain.UpdateUser]{
	Name:     "UpdateUser",
	Document: domain.UpdateUserDocument,
}

type UserOperationVars struct {
	ArticleID  string         `json:"articleId"`
	MetadataID string         `json:"metadataId"`
	Size       *int           `json:"size"`
	UserID     *string        `json:"userId"`
	UserStatus *domain.Status `json:"userStatus"`
}

var UserOperationOp = client.Operation[client.Query, UserOperationVars, domain.UserOperation]{
	Name:     "UserOperation",
	Document: domain.UserOperationDocument,
}

type CountVars struct {
	Target int `json:"target"`
}

var CountOp = client.Operation[client.Subscription, CountVars, domain.Count]{
	Name:     "Count",
	Document: domain.CountDocument,
}
