// Code generated by github.com/Yamashou/gqlgenc, DO NOT EDIT.

package query

import (
	"github.com/99designs/gqlgen/graphql"
	"github.com/Yamashou/gqlgenc/v3/client"
	"github.com/Yamashou/gqlgenc/v3/testdata/integration/basic/domain"
)

type UpdateUserVars struct {
	Input domain.UpdateUserInput `json:"input"`
}

var UpdateUserOp = client.Operation[client.Mutation, UpdateUserVars, domain.UpdateUser]{
	Name:     "UpdateUser",
	Document: domain.UpdateUserDocument,
}

type UserOperationVars struct {
	ArticleID    string                            `json:"articleId"`
	MetadataID   string                            `json:"metadataId"`
	Size         graphql.Omittable[*int]           `json:"size,omitzero"`
	UserID       graphql.Omittable[*string]        `json:"userId,omitzero"`
	UserStatus   graphql.Omittable[*domain.Status] `json:"userStatus,omitzero"`
	IncludeEmail bool                              `json:"includeEmail"`
	SkipName     bool                              `json:"skipName"`
}

var UserOperationOp = client.Operation[client.Query, UserOperationVars, domain.UserOperation]{
	Name:     "UserOperation",
	Document: domain.UserOperationDocument,
}

type CountVars struct {
	Target int `json:"target"`
}

var CountOp = client.Operation[client.Subscription, CountVars, domain.Count]{
	Name:     "Count",
	Document: domain.CountDocument,
}
