schema:
  - ./schema/schema.graphql
model:
  filename: ./model/models_gen.go
client:
  filename: ./gen/client.go
models:
  Number:
    model: github.com/gqlgo/gqlgenc/example/input-scalar/scalar.Number
query:
  - "./query/*.graphql"
generate:
  clientV2: true
  clientInterfaceName: "GithubGraphQLClient"
