// Code generated by github.com/Yamashou/gqlgenc, DO NOT EDIT.

package domain

type Search struct {
	Search []string "json:\"search\""
}

const SearchDocument = `query Search($filters: [FilterInput!]!, $ids: [ID!]!, $matrix: [[String!]]) { search(filters: $filters, ids: $ids, matrix: $matrix) }`
