// Code generated by github.com/gqlgo/gqlgenc, DO NOT EDIT.

package actual

import (
	"context"

	"github.com/gqlgo/gqlgenc/clientv2"
	domain "github.com/gqlgo/gqlgenc/generator/testdata/client_only/model"
)

type Client struct {
	Client *clientv2.Client
}

func NewClient(cli clientv2.HttpClient, baseURL string, options *clientv2.Options, interceptors ...clientv2.RequestInterceptor) *Client {
	return &Client{Client: clientv2.NewClient(cli, baseURL, options, interceptors...)}
}

type GetItem_Item struct {
	ID     string        "json:\"id\" graphql:\"id\""
	Name   string        "json:\"name\" graphql:\"name\""
	Status domain.Status "json:\"status\" graphql:\"status\""
}

func (t *GetItem_Item) GetID() string {
	if t == nil {
		t = &GetItem_Item{}
	}
	return t.ID
}
func (t *GetItem_Item) GetName() string {
	if t == nil {
		t = &GetItem_Item{}
	}
	return t.Name
}
func (t *GetItem_Item) GetStatus() *domain.Status {
	if t == nil {
		t = &GetItem_Item{}
	}
	return &t.Status
}

type GetItem struct {
	Item *GetItem_Item "json:\"item,omitempty\" graphql:\"item\""
}

func (t *GetItem) GetItem() *GetItem_Item {
	if t == nil {
		t = &GetItem{}
	}
	return t.Item
}

const GetItemDocument = `query GetItem {
	item {
		id
		status
		name
	}
}
`

func (c *Client) GetItem(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*GetItem, error) {
	vars := map[string]any{}

	var res GetItem
	if err := c.Client.Post(ctx, "GetItem", GetItemDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

var DocumentOperationNames = map[string]string{
	GetItemDocument: "GetItem",
}
