// Code generated by github.com/gqlgo/gqlgenc, DO NOT EDIT.

package generated

import (
	"context"

	"github.com/gqlgo/gqlgenc/clientv2"
)

type Client struct {
	Client *clientv2.Client
}

func NewClient(cli clientv2.HttpClient, baseURL string, options *clientv2.Options, interceptors ...clientv2.RequestInterceptor) *Client {
	return &Client{Client: clientv2.NewClient(cli, baseURL, options, interceptors...)}
}

type UserProfile struct {
	Name    string               "json:\"name\" graphql:\"name\""
	Profile *UserProfile_Profile "json:\"profile,omitempty\" graphql:\"profile\""
}

func (t *UserProfile) GetName() string {
	if t == nil {
		t = &UserProfile{}
	}
	return t.Name
}
func (t *UserProfile) GetProfile() *UserProfile_Profile {
	if t == nil {
		t = &UserProfile{}
	}
	return t.Profile
}

type UserProfile_Profile struct {
	Bio *string "json:\"bio,omitempty\" graphql:\"bio\""
}

func (t *UserProfile_Profile) GetBio() *string {
	if t == nil {
		t = &UserProfile_Profile{}
	}
	return t.Bio
}

type GetUser_User_UserProfile_Profile struct {
	Bio *string "json:\"bio,omitempty\" graphql:\"bio\""
}

func (t *GetUser_User_UserProfile_Profile) GetBio() *string {
	if t == nil {
		t = &GetUser_User_UserProfile_Profile{}
	}
	return t.Bio
}

type GetUser_User struct {
	ID      string                            "json:\"id\" graphql:\"id\""
	Name    string                            "json:\"name\" graphql:\"name\""
	Profile *GetUser_User_UserProfile_Profile "json:\"profile,omitempty\" graphql:\"profile\""
}

func (t *GetUser_User) GetID() string {
	if t == nil {
		t = &GetUser_User{}
	}
	return t.ID
}
func (t *GetUser_User) GetName() string {
	if t == nil {
		t = &GetUser_User{}
	}
	return t.Name
}
func (t *GetUser_User) GetProfile() *GetUser_User_UserProfile_Profile {
	if t == nil {
		t = &GetUser_User{}
	}
	return t.Profile
}

type GetUserDirect_User_Profile struct {
	Avatar *string "json:\"avatar,omitempty\" graphql:\"avatar\""
	Bio    *string "json:\"bio,omitempty\" graphql:\"bio\""
}

func (t *GetUserDirect_User_Profile) GetAvatar() *string {
	if t == nil {
		t = &GetUserDirect_User_Profile{}
	}
	return t.Avatar
}
func (t *GetUserDirect_User_Profile) GetBio() *string {
	if t == nil {
		t = &GetUserDirect_User_Profile{}
	}
	return t.Bio
}

type GetUserDirect_User struct {
	ID      string                      "json:\"id\" graphql:\"id\""
	Name    string                      "json:\"name\" graphql:\"name\""
	Profile *GetUserDirect_User_Profile "json:\"profile,omitempty\" graphql:\"profile\""
}

func (t *GetUserDirect_User) GetID() string {
	if t == nil {
		t = &GetUserDirect_User{}
	}
	return t.ID
}
func (t *GetUserDirect_User) GetName() string {
	if t == nil {
		t = &GetUserDirect_User{}
	}
	return t.Name
}
func (t *GetUserDirect_User) GetProfile() *GetUserDirect_User_Profile {
	if t == nil {
		t = &GetUserDirect_User{}
	}
	return t.Profile
}

type GetUser struct {
	User GetUser_User "json:\"user\" graphql:\"user\""
}

func (t *GetUser) GetUser() *GetUser_User {
	if t == nil {
		t = &GetUser{}
	}
	return &t.User
}

type GetUserDirect struct {
	User GetUserDirect_User "json:\"user\" graphql:\"user\""
}

func (t *GetUserDirect) GetUser() *GetUserDirect_User {
	if t == nil {
		t = &GetUserDirect{}
	}
	return &t.User
}

const GetUserDocument = `query GetUser ($id: ID!) {
	user(id: $id) {
		... UserProfile
		id @dummy_custom(value: "user-789")
	}
}
fragment UserProfile on User {
	name @dummy_custom(value: "Alice")
	profile {
		bio @dummy_custom(value: "Software engineer")
	}
}
`

func (c *Client) GetUser(ctx context.Context, id string, interceptors ...clientv2.RequestInterceptor) (*GetUser, error) {
	vars := map[string]any{
		"id": id,
	}

	var res GetUser
	if err := c.Client.Post(ctx, "GetUser", GetUserDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const GetUserDirectDocument = `query GetUserDirect ($id: ID!) {
	user(id: $id) {
		id @dummy_custom(value: "user-direct")
		name @dummy_custom(value: "Bob")
		profile {
			bio @dummy_custom(value: "Designer")
			avatar @dummy_custom(value: "https://example.com/bob.png")
		}
	}
}
`

func (c *Client) GetUserDirect(ctx context.Context, id string, interceptors ...clientv2.RequestInterceptor) (*GetUserDirect, error) {
	vars := map[string]any{
		"id": id,
	}

	var res GetUserDirect
	if err := c.Client.Post(ctx, "GetUserDirect", GetUserDirectDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

var DocumentOperationNames = map[string]string{
	GetUserDocument:       "GetUser",
	GetUserDirectDocument: "GetUserDirect",
}
