// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package generated

type Profile struct {
	Bio    *string `json:"bio,omitempty"`
	Avatar *string `json:"avatar,omitempty"`
}

type Query struct {
}

type User struct {
	ID      string   `json:"id"`
	Name    string   `json:"name"`
	Profile *Profile `json:"profile,omitempty"`
}
