// Code generated by github.com/gqlgo/gqlgenc, DO NOT EDIT.

package generated

import (
	"context"

	"github.com/gqlgo/gqlgenc/clientv2"
)

type UserService interface {
	GetUser(ctx context.Context, id string, interceptors ...clientv2.RequestInterceptor) (*GetUser, error)
}

type Client struct {
	Client *clientv2.Client
}

func NewClient(cli clientv2.HttpClient, baseURL string, options *clientv2.Options, interceptors ...clientv2.RequestInterceptor) UserService {
	return &Client{Client: clientv2.NewClient(cli, baseURL, options, interceptors...)}
}

type GetUser_User struct {
	ID   string "json:\"id\" graphql:\"id\""
	Name string "json:\"name\" graphql:\"name\""
}

func (t *GetUser_User) GetID() string {
	if t == nil {
		t = &GetUser_User{}
	}
	return t.ID
}
func (t *GetUser_User) GetName() string {
	if t == nil {
		t = &GetUser_User{}
	}
	return t.Name
}

type GetUser struct {
	User GetUser_User "json:\"user\" graphql:\"user\""
}

func (t *GetUser) GetUser() *GetUser_User {
	if t == nil {
		t = &GetUser{}
	}
	return &t.User
}

const GetUserDocument = `query GetUser ($id: ID!) {
	user(id: $id) {
		id
		name
	}
}
`

func (c *Client) GetUser(ctx context.Context, id string, interceptors ...clientv2.RequestInterceptor) (*GetUser, error) {
	vars := map[string]any{
		"id": id,
	}

	var res GetUser
	if err := c.Client.Post(ctx, "GetUser", GetUserDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

var DocumentOperationNames = map[string]string{
	GetUserDocument: "GetUser",
}
