// Code generated by github.com/gqlgo/gqlgenc, DO NOT EDIT.

package generated

import (
	"context"

	"github.com/gqlgo/gqlgenc/clientv2"
)

type Client struct {
	Client *clientv2.Client
}

func NewClient(cli clientv2.HttpClient, baseURL string, options *clientv2.Options, interceptors ...clientv2.RequestInterceptor) *Client {
	return &Client{Client: clientv2.NewClient(cli, baseURL, options, interceptors...)}
}

type PayloadFields struct {
	Success bool                  "json:\"success\" graphql:\"success\""
	Detail  *PayloadFields_Detail "json:\"detail,omitempty\" graphql:\"detail\""
}

func (t *PayloadFields) GetSuccess() bool {
	if t == nil {
		t = &PayloadFields{}
	}
	return t.Success
}
func (t *PayloadFields) GetDetail() *PayloadFields_Detail {
	if t == nil {
		t = &PayloadFields{}
	}
	return t.Detail
}

type PayloadFields_Detail struct {
	Code int     "json:\"code\" graphql:\"code\""
	Note *string "json:\"note,omitempty\" graphql:\"note\""
}

func (t *PayloadFields_Detail) GetCode() int {
	if t == nil {
		t = &PayloadFields_Detail{}
	}
	return t.Code
}
func (t *PayloadFields_Detail) GetNote() *string {
	if t == nil {
		t = &PayloadFields_Detail{}
	}
	return t.Note
}

type InFragment_Payload_PayloadFields_Detail struct {
	Code int     "json:\"code\" graphql:\"code\""
	Note *string "json:\"note,omitempty\" graphql:\"note\""
}

func (t *InFragment_Payload_PayloadFields_Detail) GetCode() int {
	if t == nil {
		t = &InFragment_Payload_PayloadFields_Detail{}
	}
	return t.Code
}
func (t *InFragment_Payload_PayloadFields_Detail) GetNote() *string {
	if t == nil {
		t = &InFragment_Payload_PayloadFields_Detail{}
	}
	return t.Note
}

type InInlineFragment_Payload_XXXPayload struct {
	Success bool    "json:\"success\" graphql:\"success\""
	Message *string "json:\"message,omitempty\" graphql:\"message\""
}

func (t *InInlineFragment_Payload_XXXPayload) GetSuccess() bool {
	if t == nil {
		t = &InInlineFragment_Payload_XXXPayload{}
	}
	return t.Success
}
func (t *InInlineFragment_Payload_XXXPayload) GetMessage() *string {
	if t == nil {
		t = &InInlineFragment_Payload_XXXPayload{}
	}
	return t.Message
}

type AtTopLevel_Payload struct {
	Message *string "json:\"message,omitempty\" graphql:\"message\""
	Success bool    "json:\"success\" graphql:\"success\""
}

func (t *AtTopLevel_Payload) GetMessage() *string {
	if t == nil {
		t = &AtTopLevel_Payload{}
	}
	return t.Message
}
func (t *AtTopLevel_Payload) GetSuccess() bool {
	if t == nil {
		t = &AtTopLevel_Payload{}
	}
	return t.Success
}

type InFragment struct {
	Payload *PayloadFields "json:\"payload,omitempty\" graphql:\"payload\""
}

func (t *InFragment) GetPayload() *PayloadFields {
	if t == nil {
		t = &InFragment{}
	}
	return t.Payload
}

type InInlineFragment struct {
	Payload *InInlineFragment_Payload_XXXPayload "json:\"payload,omitempty\" graphql:\"payload\""
}

func (t *InInlineFragment) GetPayload() *InInlineFragment_Payload_XXXPayload {
	if t == nil {
		t = &InInlineFragment{}
	}
	return t.Payload
}

type AtTopLevel struct {
	Payload *AtTopLevel_Payload "json:\"payload,omitempty\" graphql:\"payload\""
}

func (t *AtTopLevel) GetPayload() *AtTopLevel_Payload {
	if t == nil {
		t = &AtTopLevel{}
	}
	return t.Payload
}

const InFragmentDocument = `query InFragment {
	payload {
		... PayloadFields
	}
}
fragment PayloadFields on XXXPayload {
	success
	success
	detail {
		code
	}
	detail {
		note
	}
}
`

func (c *Client) InFragment(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*InFragment, error) {
	vars := map[string]any{}

	var res InFragment
	if err := c.Client.Post(ctx, "InFragment", InFragmentDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const InInlineFragmentDocument = `query InInlineFragment {
	payload {
		... on XXXPayload {
			success
			success
			message
		}
	}
}
`

func (c *Client) InInlineFragment(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*InInlineFragment, error) {
	vars := map[string]any{}

	var res InInlineFragment
	if err := c.Client.Post(ctx, "InInlineFragment", InInlineFragmentDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const AtTopLevelDocument = `query AtTopLevel {
	payload {
		success
		success
		message
		message
	}
}
`

func (c *Client) AtTopLevel(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*AtTopLevel, error) {
	vars := map[string]any{}

	var res AtTopLevel
	if err := c.Client.Post(ctx, "AtTopLevel", AtTopLevelDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

var DocumentOperationNames = map[string]string{
	InFragmentDocument:       "InFragment",
	InInlineFragmentDocument: "InInlineFragment",
	AtTopLevelDocument:       "AtTopLevel",
}
