// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package generated

type Detail struct {
	Code int     `json:"code"`
	Note *string `json:"note,omitempty"`
}

type Query struct {
}

type XXXPayload struct {
	Success bool    `json:"success"`
	Message *string `json:"message,omitempty"`
	Detail  *Detail `json:"detail,omitempty"`
}
