// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package domain

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"github.com/99designs/gqlgen/graphql"
)

type UpdateUserInput struct {
	ID       string                                `json:"id"`
	Name     graphql.Omittable[*string]            `json:"name,omitempty,omitzero"`
	Settings graphql.Omittable[*UserSettingsInput] `json:"settings,omitempty,omitzero"`
	Tags     graphql.Omittable[[]string]           `json:"tags,omitempty,omitzero"`
}

type UserSettingsInput struct {
	Theme         string `json:"theme"`
	Notifications bool   `json:"notifications"`
}

type Status string

const (
	StatusActive   Status = "ACTIVE"
	StatusInactive Status = "INACTIVE"
)

var AllStatus = []Status{
	StatusActive,
	StatusInactive,
}

func (e Status) IsValid() bool {
	switch e {
	case StatusActive, StatusInactive:
		return true
	}
	return false
}

func (e Status) String() string {
	return string(e)
}

func (e *Status) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Status(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Status", str)
	}
	return nil
}

func (e Status) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Status) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Status) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
