// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package domain

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"github.com/99designs/gqlgen/graphql"
)

type Address interface {
	IsAddress()
	GetStreet() string
}

type Profile interface {
	IsProfile()
}

type Article struct {
	ID                   string     `json:"id"`
	Title                string     `json:"title"`
	Tags                 []string   `json:"tags"`
	OptionalTags         []string   `json:"optionalTags,omitzero"`
	Comments             []*Comment `json:"comments"`
	OptionalComments     []*Comment `json:"optionalComments,omitzero"`
	Rating               float64    `json:"rating"`
	OptionalRating       *float64   `json:"optionalRating,omitzero"`
	NullableElementsList []*string  `json:"nullableElementsList"`
	FullyNullableList    []*string  `json:"fullyNullableList,omitzero"`
	Statuses             []Status   `json:"statuses"`
	OptionalStatuses     []Status   `json:"optionalStatuses,omitzero"`
	Addresses            []Address  `json:"addresses"`
	OptionalAddresses    []Address  `json:"optionalAddresses,omitzero"`
	Profiles             []Profile  `json:"profiles"`
	OptionalProfiles     []Profile  `json:"optionalProfiles,omitzero"`
	Matrix               [][]string `json:"matrix"`
	OptionalMatrix       [][]string `json:"optionalMatrix,omitzero"`
}

type Comment struct {
	ID   string `json:"id"`
	Text string `json:"text"`
}

type Metadata struct {
	ID   string  `json:"id"`
	Data *string `json:"data,omitzero"`
}

type Mutation struct {
}

type PrivateAddress struct {
	ID      string `json:"id"`
	Street  string `json:"street"`
	Private bool   `json:"private"`
}

func (PrivateAddress) IsAddress()             {}
func (this PrivateAddress) GetStreet() string { return this.Street }

type PrivateProfile struct {
	ID  string `json:"id"`
	Age *int   `json:"age,omitzero"`
}

func (PrivateProfile) IsProfile() {}

type PublicAddress struct {
	ID     string `json:"id"`
	Street string `json:"street"`
	Public bool   `json:"public"`
}

func (PublicAddress) IsAddress()             {}
func (this PublicAddress) GetStreet() string { return this.Street }

type PublicProfile struct {
	ID     string `json:"id"`
	Status Status `json:"status"`
}

func (PublicProfile) IsProfile() {}

type Query struct {
}

type UpdateUserInput struct {
	ID       UserID                                `json:"id"`
	Name     graphql.Omittable[*string]            `json:"name,omitzero"`
	Settings graphql.Omittable[*UserSettingsInput] `json:"settings,omitzero"`
	Tags     graphql.Omittable[[]string]           `json:"tags,omitzero"`
}

type UpdateUserPayload struct {
	User *User `json:"user"`
}

type UserSettings struct {
	Theme         string `json:"theme"`
	Notifications bool   `json:"notifications"`
}

type UserSettingsInput struct {
	Theme         string `json:"theme"`
	Notifications bool   `json:"notifications"`
}

type Status string

const (
	StatusActive   Status = "ACTIVE"
	StatusInactive Status = "INACTIVE"
)

var AllStatus = []Status{
	StatusActive,
	StatusInactive,
}

func (e Status) IsValid() bool {
	switch e {
	case StatusActive, StatusInactive:
		return true
	}
	return false
}

func (e Status) String() string {
	return string(e)
}

func (e *Status) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Status(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Status", str)
	}
	return nil
}

func (e Status) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Status) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Status) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
