// Code generated by github.com/Yamashou/gqlgenc, DO NOT EDIT.

package domain

import (
	"encoding/json/jsontext"
	json "encoding/json/v2"
)

type Count struct {
	Count int "json:\"count\""
}

func (t *Count) GetCount() int {
	if t == nil {
		t = &Count{}
	}
	return t.Count
}

type PrivateAddressFields struct {
	ID      string "json:\"id\""
	Private bool   "json:\"private\""
	Street  string "json:\"street\""
}

func (t *PrivateAddressFields) GetID() string {
	if t == nil {
		t = &PrivateAddressFields{}
	}
	return t.ID
}
func (t *PrivateAddressFields) GetPrivate() bool {
	if t == nil {
		t = &PrivateAddressFields{}
	}
	return t.Private
}
func (t *PrivateAddressFields) GetStreet() string {
	if t == nil {
		t = &PrivateAddressFields{}
	}
	return t.Street
}

type PrivateProfileFields struct {
	Age *int   "json:\"age\""
	ID  string "json:\"id\""
}

func (t *PrivateProfileFields) GetAge() *int {
	if t == nil {
		t = &PrivateProfileFields{}
	}
	return t.Age
}
func (t *PrivateProfileFields) GetID() string {
	if t == nil {
		t = &PrivateProfileFields{}
	}
	return t.ID
}

type PublicProfileFields struct {
	ID     string "json:\"id\""
	Status Status "json:\"status\""
}

func (t *PublicProfileFields) GetID() string {
	if t == nil {
		t = &PublicProfileFields{}
	}
	return t.ID
}
func (t *PublicProfileFields) GetStatus() Status {
	if t == nil {
		t = &PublicProfileFields{}
	}
	return t.Status
}

type UpdateUser struct {
	UpdateUser UpdateUser_UpdateUser "json:\"updateUser\""
}

func (t *UpdateUser) GetUpdateUser() UpdateUser_UpdateUser {
	if t == nil {
		t = &UpdateUser{}
	}
	return t.UpdateUser
}

type UpdateUser_UpdateUser struct {
	User UpdateUser_UpdateUser_User "json:\"user\""
}

func (t *UpdateUser_UpdateUser) GetUser() UpdateUser_UpdateUser_User {
	if t == nil {
		t = &UpdateUser_UpdateUser{}
	}
	return t.User
}

type UpdateUser_UpdateUser_User struct {
	Name     string                               "json:\"name\""
	Settings *UpdateUser_UpdateUser_User_Settings "json:\"settings\""
}

func (t *UpdateUser_UpdateUser_User) GetName() string {
	if t == nil {
		t = &UpdateUser_UpdateUser_User{}
	}
	return t.Name
}
func (t *UpdateUser_UpdateUser_User) GetSettings() *UpdateUser_UpdateUser_User_Settings {
	if t == nil {
		t = &UpdateUser_UpdateUser_User{}
	}
	return t.Settings
}

type UpdateUser_UpdateUser_User_Settings struct {
	Notifications bool   "json:\"notifications\""
	Theme         string "json:\"theme\""
}

func (t *UpdateUser_UpdateUser_User_Settings) GetNotifications() bool {
	if t == nil {
		t = &UpdateUser_UpdateUser_User_Settings{}
	}
	return t.Notifications
}
func (t *UpdateUser_UpdateUser_User_Settings) GetTheme() string {
	if t == nil {
		t = &UpdateUser_UpdateUser_User_Settings{}
	}
	return t.Theme
}

type UserFragment1 struct {
	User *struct {
		Name string "json:\"name\""
	} "json:\"-\""
	Typename string                "json:\"__typename\""
	Name     string                "json:\"name\""
	Profile  UserFragment1_Profile "json:\"profile\""
}

func (t *UserFragment1) GetUser() *struct {
	Name string "json:\"name\""
} {
	if t == nil {
		t = &UserFragment1{}
	}
	return t.User
}
func (t *UserFragment1) GetTypename() string {
	if t == nil {
		t = &UserFragment1{}
	}
	return t.Typename
}
func (t *UserFragment1) GetName() string {
	if t == nil {
		t = &UserFragment1{}
	}
	return t.Name
}
func (t *UserFragment1) GetProfile() UserFragment1_Profile {
	if t == nil {
		t = &UserFragment1{}
	}
	return t.Profile
}

type UserFragment1_Profile struct {
	PrivateProfile *struct {
		Age *int "json:\"age\""
	} "json:\"-\""
	PublicProfile *struct {
		Status Status "json:\"status\""
	} "json:\"-\""
	Typename string "json:\"__typename\""
}

func (t *UserFragment1_Profile) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	data, err := dec.ReadValue()
	if err != nil {
		return err
	}
	type plain UserFragment1_Profile
	if err := json.Unmarshal(data, (*plain)(t)); err != nil {
		return err
	}
	switch t.Typename {
	case "PrivateProfile":
		if err := json.Unmarshal(data, &t.PrivateProfile); err != nil {
			return err
		}
	case "PublicProfile":
		if err := json.Unmarshal(data, &t.PublicProfile); err != nil {
			return err
		}
	}
	return nil
}
func (t *UserFragment1_Profile) GetPrivateProfile() *struct {
	Age *int "json:\"age\""
} {
	if t == nil {
		t = &UserFragment1_Profile{}
	}
	return t.PrivateProfile
}
func (t *UserFragment1_Profile) GetPublicProfile() *struct {
	Status Status "json:\"status\""
} {
	if t == nil {
		t = &UserFragment1_Profile{}
	}
	return t.PublicProfile
}
func (t *UserFragment1_Profile) GetTypename() string {
	if t == nil {
		t = &UserFragment1_Profile{}
	}
	return t.Typename
}

type UserOperation struct {
	Article      *UserOperation_Article      "json:\"article\""
	Metadata     *UserOperation_Metadata     "json:\"metadata\""
	OptionalUser *UserOperation_OptionalUser "json:\"optionalUser\""
	User         UserOperation_User          "json:\"user\""
}

func (t *UserOperation) GetArticle() *UserOperation_Article {
	if t == nil {
		t = &UserOperation{}
	}
	return t.Article
}
func (t *UserOperation) GetMetadata() *UserOperation_Metadata {
	if t == nil {
		t = &UserOperation{}
	}
	return t.Metadata
}
func (t *UserOperation) GetOptionalUser() *UserOperation_OptionalUser {
	if t == nil {
		t = &UserOperation{}
	}
	return t.OptionalUser
}
func (t *UserOperation) GetUser() UserOperation_User {
	if t == nil {
		t = &UserOperation{}
	}
	return t.User
}

type UserOperation_Article struct {
	Addresses            []*UserOperation_Article_Addresses          "json:\"addresses\""
	Comments             []*UserOperation_Article_Comments           "json:\"comments\""
	FullyNullableList    *[]*string                                  "json:\"fullyNullableList\""
	ID                   string                                      "json:\"id\""
	Matrix               [][]string                                  "json:\"matrix\""
	NullableElementsList []*string                                   "json:\"nullableElementsList\""
	OptionalAddresses    *[]*UserOperation_Article_OptionalAddresses "json:\"optionalAddresses\""
	OptionalComments     *[]*UserOperation_Article_OptionalComments  "json:\"optionalComments\""
	OptionalMatrix       *[][]string                                 "json:\"optionalMatrix\""
	OptionalProfiles     *[]*UserOperation_Article_OptionalProfiles  "json:\"optionalProfiles\""
	OptionalRating       *float64                                    "json:\"optionalRating\""
	OptionalStatuses     *[]Status                                   "json:\"optionalStatuses\""
	OptionalTags         *[]string                                   "json:\"optionalTags\""
	Profiles             []*UserOperation_Article_Profiles           "json:\"profiles\""
	Rating               float64                                     "json:\"rating\""
	Statuses             []Status                                    "json:\"statuses\""
	Tags                 []string                                    "json:\"tags\""
	Title                string                                      "json:\"title\""
}

func (t *UserOperation_Article) GetAddresses() []*UserOperation_Article_Addresses {
	if t == nil {
		t = &UserOperation_Article{}
	}
	return t.Addresses
}
func (t *UserOperation_Article) GetComments() []*UserOperation_Article_Comments {
	if t == nil {
		t = &UserOperation_Article{}
	}
	return t.Comments
}
func (t *UserOperation_Article) GetFullyNullableList() *[]*string {
	if t == nil {
		t = &UserOperation_Article{}
	}
	return t.FullyNullableList
}
func (t *UserOperation_Article) GetID() string {
	if t == nil {
		t = &UserOperation_Article{}
	}
	return t.ID
}
func (t *UserOperation_Article) GetMatrix() [][]string {
	if t == nil {
		t = &UserOperation_Article{}
	}
	return t.Matrix
}
func (t *UserOperation_Article) GetNullableElementsList() []*string {
	if t == nil {
		t = &UserOperation_Article{}
	}
	return t.NullableElementsList
}
func (t *UserOperation_Article) GetOptionalAddresses() *[]*UserOperation_Article_OptionalAddresses {
	if t == nil {
		t = &UserOperation_Article{}
	}
	return t.OptionalAddresses
}
func (t *UserOperation_Article) GetOptionalComments() *[]*UserOperation_Article_OptionalComments {
	if t == nil {
		t = &UserOperation_Article{}
	}
	return t.OptionalComments
}
func (t *UserOperation_Article) GetOptionalMatrix() *[][]string {
	if t == nil {
		t = &UserOperation_Article{}
	}
	return t.OptionalMatrix
}
func (t *UserOperation_Article) GetOptionalProfiles() *[]*UserOperation_Article_OptionalProfiles {
	if t == nil {
		t = &UserOperation_Article{}
	}
	return t.OptionalProfiles
}
func (t *UserOperation_Article) GetOptionalRating() *float64 {
	if t == nil {
		t = &UserOperation_Article{}
	}
	return t.OptionalRating
}
func (t *UserOperation_Article) GetOptionalStatuses() *[]Status {
	if t == nil {
		t = &UserOperation_Article{}
	}
	return t.OptionalStatuses
}
func (t *UserOperation_Article) GetOptionalTags() *[]string {
	if t == nil {
		t = &UserOperation_Article{}
	}
	return t.OptionalTags
}
func (t *UserOperation_Article) GetProfiles() []*UserOperation_Article_Profiles {
	if t == nil {
		t = &UserOperation_Article{}
	}
	return t.Profiles
}
func (t *UserOperation_Article) GetRating() float64 {
	if t == nil {
		t = &UserOperation_Article{}
	}
	return t.Rating
}
func (t *UserOperation_Article) GetStatuses() []Status {
	if t == nil {
		t = &UserOperation_Article{}
	}
	return t.Statuses
}
func (t *UserOperation_Article) GetTags() []string {
	if t == nil {
		t = &UserOperation_Article{}
	}
	return t.Tags
}
func (t *UserOperation_Article) GetTitle() string {
	if t == nil {
		t = &UserOperation_Article{}
	}
	return t.Title
}

type UserOperation_Article_Addresses struct {
	AddressView          "json:\"-\""
	PrivateAddressFields "json:\"-\""
	Street               string "json:\"street\""
}

func (t *UserOperation_Article_Addresses) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	data, err := dec.ReadValue()
	if err != nil {
		return err
	}
	type plain UserOperation_Article_Addresses
	if err := json.Unmarshal(data, (*plain)(t)); err != nil {
		return err
	}
	if err := json.Unmarshal(data, &t.AddressView); err != nil {
		return err
	}
	if err := json.Unmarshal(data, &t.PrivateAddressFields); err != nil {
		return err
	}
	return nil
}
func (t *UserOperation_Article_Addresses) GetAddressView() AddressView {
	if t == nil {
		t = &UserOperation_Article_Addresses{}
	}
	return t.AddressView
}
func (t *UserOperation_Article_Addresses) GetPrivateAddressFields() PrivateAddressFields {
	if t == nil {
		t = &UserOperation_Article_Addresses{}
	}
	return t.PrivateAddressFields
}
func (t *UserOperation_Article_Addresses) GetStreet() string {
	if t == nil {
		t = &UserOperation_Article_Addresses{}
	}
	return t.Street
}

type UserOperation_Article_Comments struct {
	ID   string "json:\"id\""
	Text string "json:\"text\""
}

func (t *UserOperation_Article_Comments) GetID() string {
	if t == nil {
		t = &UserOperation_Article_Comments{}
	}
	return t.ID
}
func (t *UserOperation_Article_Comments) GetText() string {
	if t == nil {
		t = &UserOperation_Article_Comments{}
	}
	return t.Text
}

type UserOperation_Article_OptionalAddresses struct {
	PrivateAddress *struct {
		Private bool "json:\"private\""
	} "json:\"-\""
	PublicAddress *struct {
		Public bool "json:\"public\""
	} "json:\"-\""
	Typename string "json:\"__typename\""
	Street   string "json:\"street\""
}

func (t *UserOperation_Article_OptionalAddresses) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	data, err := dec.ReadValue()
	if err != nil {
		return err
	}
	type plain UserOperation_Article_OptionalAddresses
	if err := json.Unmarshal(data, (*plain)(t)); err != nil {
		return err
	}
	switch t.Typename {
	case "PrivateAddress":
		if err := json.Unmarshal(data, &t.PrivateAddress); err != nil {
			return err
		}
	case "PublicAddress":
		if err := json.Unmarshal(data, &t.PublicAddress); err != nil {
			return err
		}
	}
	return nil
}
func (t *UserOperation_Article_OptionalAddresses) GetPrivateAddress() *struct {
	Private bool "json:\"private\""
} {
	if t == nil {
		t = &UserOperation_Article_OptionalAddresses{}
	}
	return t.PrivateAddress
}
func (t *UserOperation_Article_OptionalAddresses) GetPublicAddress() *struct {
	Public bool "json:\"public\""
} {
	if t == nil {
		t = &UserOperation_Article_OptionalAddresses{}
	}
	return t.PublicAddress
}
func (t *UserOperation_Article_OptionalAddresses) GetTypename() string {
	if t == nil {
		t = &UserOperation_Article_OptionalAddresses{}
	}
	return t.Typename
}
func (t *UserOperation_Article_OptionalAddresses) GetStreet() string {
	if t == nil {
		t = &UserOperation_Article_OptionalAddresses{}
	}
	return t.Street
}

type UserOperation_Article_OptionalComments struct {
	ID   string "json:\"id\""
	Text string "json:\"text\""
}

func (t *UserOperation_Article_OptionalComments) GetID() string {
	if t == nil {
		t = &UserOperation_Article_OptionalComments{}
	}
	return t.ID
}
func (t *UserOperation_Article_OptionalComments) GetText() string {
	if t == nil {
		t = &UserOperation_Article_OptionalComments{}
	}
	return t.Text
}

type UserOperation_Article_OptionalProfiles struct {
	PrivateProfile *struct {
		Age *int "json:\"age\""
	} "json:\"-\""
	PublicProfile *struct {
		Status Status "json:\"status\""
	} "json:\"-\""
	Typename string "json:\"__typename\""
}

func (t *UserOperation_Article_OptionalProfiles) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	data, err := dec.ReadValue()
	if err != nil {
		return err
	}
	type plain UserOperation_Article_OptionalProfiles
	if err := json.Unmarshal(data, (*plain)(t)); err != nil {
		return err
	}
	switch t.Typename {
	case "PrivateProfile":
		if err := json.Unmarshal(data, &t.PrivateProfile); err != nil {
			return err
		}
	case "PublicProfile":
		if err := json.Unmarshal(data, &t.PublicProfile); err != nil {
			return err
		}
	}
	return nil
}
func (t *UserOperation_Article_OptionalProfiles) GetPrivateProfile() *struct {
	Age *int "json:\"age\""
} {
	if t == nil {
		t = &UserOperation_Article_OptionalProfiles{}
	}
	return t.PrivateProfile
}
func (t *UserOperation_Article_OptionalProfiles) GetPublicProfile() *struct {
	Status Status "json:\"status\""
} {
	if t == nil {
		t = &UserOperation_Article_OptionalProfiles{}
	}
	return t.PublicProfile
}
func (t *UserOperation_Article_OptionalProfiles) GetTypename() string {
	if t == nil {
		t = &UserOperation_Article_OptionalProfiles{}
	}
	return t.Typename
}

type UserOperation_Article_Profiles struct {
	PrivateProfileFields "json:\"-\""
	PublicProfileFields  "json:\"-\""
}

func (t *UserOperation_Article_Profiles) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	data, err := dec.ReadValue()
	if err != nil {
		return err
	}
	if err := json.Unmarshal(data, &t.PrivateProfileFields); err != nil {
		return err
	}
	if err := json.Unmarshal(data, &t.PublicProfileFields); err != nil {
		return err
	}
	return nil
}
func (t *UserOperation_Article_Profiles) GetPrivateProfileFields() PrivateProfileFields {
	if t == nil {
		t = &UserOperation_Article_Profiles{}
	}
	return t.PrivateProfileFields
}
func (t *UserOperation_Article_Profiles) GetPublicProfileFields() PublicProfileFields {
	if t == nil {
		t = &UserOperation_Article_Profiles{}
	}
	return t.PublicProfileFields
}

type UserOperation_Metadata struct {
	Data       *string         "json:\"data\""
	ID         string          "json:\"id\""
	Level      Level           "json:\"level\""
	Properties *map[string]any "json:\"properties\""
}

func (t *UserOperation_Metadata) GetData() *string {
	if t == nil {
		t = &UserOperation_Metadata{}
	}
	return t.Data
}
func (t *UserOperation_Metadata) GetID() string {
	if t == nil {
		t = &UserOperation_Metadata{}
	}
	return t.ID
}
func (t *UserOperation_Metadata) GetLevel() Level {
	if t == nil {
		t = &UserOperation_Metadata{}
	}
	return t.Level
}
func (t *UserOperation_Metadata) GetProperties() *map[string]any {
	if t == nil {
		t = &UserOperation_Metadata{}
	}
	return t.Properties
}

type UserOperation_OptionalUser struct {
	Email Email  "json:\"email\""
	Name  string "json:\"name\""
}

func (t *UserOperation_OptionalUser) GetEmail() Email {
	if t == nil {
		t = &UserOperation_OptionalUser{}
	}
	return t.Email
}
func (t *UserOperation_OptionalUser) GetName() string {
	if t == nil {
		t = &UserOperation_OptionalUser{}
	}
	return t.Name
}

type UserOperation_User struct {
	User *struct {
		UserFragment2 "json:\"-\""
		Name          string "json:\"name\""
	} "json:\"-\""
	UserFragment1   "json:\"-\""
	UserFragment2   "json:\"-\""
	Typename        string                              "json:\"__typename\""
	Address         UserOperation_User_Address          "json:\"address\""
	DefaultPic      string                              "json:\"defaultPic\""
	Email           Email                               "json:\"email\""
	LargePic        string                              "json:\"largePic\""
	Name            string                              "json:\"name\""
	Name2           string                              "json:\"name2\""
	OptionalAddress *UserOperation_User_OptionalAddress "json:\"optionalAddress\""
	OptionalProfile *UserOperation_User_OptionalProfile "json:\"optionalProfile\""
	Profile         UserOperation_User_Profile          "json:\"profile\""
	Profile2        UserOperation_User_Profile2         "json:\"profile2\""
	SmallPic        string                              "json:\"smallPic\""
}

func (t *UserOperation_User) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	data, err := dec.ReadValue()
	if err != nil {
		return err
	}
	type plain UserOperation_User
	if err := json.Unmarshal(data, (*plain)(t)); err != nil {
		return err
	}
	if err := json.Unmarshal(data, &t.UserFragment1); err != nil {
		return err
	}
	switch t.UserFragment1.Typename {
	case "User":
		if err := json.Unmarshal(data, &t.UserFragment1.User); err != nil {
			return err
		}
	}
	if err := json.Unmarshal(data, &t.UserFragment2); err != nil {
		return err
	}
	switch t.Typename {
	case "User":
		if err := json.Unmarshal(data, &t.User); err != nil {
			return err
		}
		if err := json.Unmarshal(data, &t.User.UserFragment2); err != nil {
			return err
		}
	}
	return nil
}
func (t *UserOperation_User) GetUser() *struct {
	UserFragment2 "json:\"-\""
	Name          string "json:\"name\""
} {
	if t == nil {
		t = &UserOperation_User{}
	}
	return t.User
}
func (t *UserOperation_User) GetUserFragment1() UserFragment1 {
	if t == nil {
		t = &UserOperation_User{}
	}
	return t.UserFragment1
}
func (t *UserOperation_User) GetUserFragment2() UserFragment2 {
	if t == nil {
		t = &UserOperation_User{}
	}
	return t.UserFragment2
}
func (t *UserOperation_User) GetTypename() string {
	if t == nil {
		t = &UserOperation_User{}
	}
	return t.Typename
}
func (t *UserOperation_User) GetAddress() UserOperation_User_Address {
	if t == nil {
		t = &UserOperation_User{}
	}
	return t.Address
}
func (t *UserOperation_User) GetDefaultPic() string {
	if t == nil {
		t = &UserOperation_User{}
	}
	return t.DefaultPic
}
func (t *UserOperation_User) GetEmail() Email {
	if t == nil {
		t = &UserOperation_User{}
	}
	return t.Email
}
func (t *UserOperation_User) GetLargePic() string {
	if t == nil {
		t = &UserOperation_User{}
	}
	return t.LargePic
}
func (t *UserOperation_User) GetName() string {
	if t == nil {
		t = &UserOperation_User{}
	}
	return t.Name
}
func (t *UserOperation_User) GetName2() string {
	if t == nil {
		t = &UserOperation_User{}
	}
	return t.Name2
}
func (t *UserOperation_User) GetOptionalAddress() *UserOperation_User_OptionalAddress {
	if t == nil {
		t = &UserOperation_User{}
	}
	return t.OptionalAddress
}
func (t *UserOperation_User) GetOptionalProfile() *UserOperation_User_OptionalProfile {
	if t == nil {
		t = &UserOperation_User{}
	}
	return t.OptionalProfile
}
func (t *UserOperation_User) GetProfile() UserOperation_User_Profile {
	if t == nil {
		t = &UserOperation_User{}
	}
	return t.Profile
}
func (t *UserOperation_User) GetProfile2() UserOperation_User_Profile2 {
	if t == nil {
		t = &UserOperation_User{}
	}
	return t.Profile2
}
func (t *UserOperation_User) GetSmallPic() string {
	if t == nil {
		t = &UserOperation_User{}
	}
	return t.SmallPic
}

type UserOperation_User_Address struct {
	AddressView          "json:\"-\""
	PrivateAddressFields "json:\"-\""
	Street               string "json:\"street\""
}

func (t *UserOperation_User_Address) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	data, err := dec.ReadValue()
	if err != nil {
		return err
	}
	type plain UserOperation_User_Address
	if err := json.Unmarshal(data, (*plain)(t)); err != nil {
		return err
	}
	if err := json.Unmarshal(data, &t.AddressView); err != nil {
		return err
	}
	if err := json.Unmarshal(data, &t.PrivateAddressFields); err != nil {
		return err
	}
	return nil
}
func (t *UserOperation_User_Address) GetAddressView() AddressView {
	if t == nil {
		t = &UserOperation_User_Address{}
	}
	return t.AddressView
}
func (t *UserOperation_User_Address) GetPrivateAddressFields() PrivateAddressFields {
	if t == nil {
		t = &UserOperation_User_Address{}
	}
	return t.PrivateAddressFields
}
func (t *UserOperation_User_Address) GetStreet() string {
	if t == nil {
		t = &UserOperation_User_Address{}
	}
	return t.Street
}

type UserOperation_User_OptionalAddress struct {
	PrivateAddress *struct {
		Private bool   "json:\"private\""
		Street  string "json:\"street\""
	} "json:\"-\""
	PublicAddress *struct {
		Public bool   "json:\"public\""
		Street string "json:\"street\""
	} "json:\"-\""
	Typename string "json:\"__typename\""
	Street   string "json:\"street\""
}

func (t *UserOperation_User_OptionalAddress) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	data, err := dec.ReadValue()
	if err != nil {
		return err
	}
	type plain UserOperation_User_OptionalAddress
	if err := json.Unmarshal(data, (*plain)(t)); err != nil {
		return err
	}
	switch t.Typename {
	case "PrivateAddress":
		if err := json.Unmarshal(data, &t.PrivateAddress); err != nil {
			return err
		}
	case "PublicAddress":
		if err := json.Unmarshal(data, &t.PublicAddress); err != nil {
			return err
		}
	}
	return nil
}
func (t *UserOperation_User_OptionalAddress) GetPrivateAddress() *struct {
	Private bool   "json:\"private\""
	Street  string "json:\"street\""
} {
	if t == nil {
		t = &UserOperation_User_OptionalAddress{}
	}
	return t.PrivateAddress
}
func (t *UserOperation_User_OptionalAddress) GetPublicAddress() *struct {
	Public bool   "json:\"public\""
	Street string "json:\"street\""
} {
	if t == nil {
		t = &UserOperation_User_OptionalAddress{}
	}
	return t.PublicAddress
}
func (t *UserOperation_User_OptionalAddress) GetTypename() string {
	if t == nil {
		t = &UserOperation_User_OptionalAddress{}
	}
	return t.Typename
}
func (t *UserOperation_User_OptionalAddress) GetStreet() string {
	if t == nil {
		t = &UserOperation_User_OptionalAddress{}
	}
	return t.Street
}

type UserOperation_User_OptionalProfile struct {
	PrivateProfileFields "json:\"-\""
	PublicProfileFields  "json:\"-\""
}

func (t *UserOperation_User_OptionalProfile) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	data, err := dec.ReadValue()
	if err != nil {
		return err
	}
	if err := json.Unmarshal(data, &t.PrivateProfileFields); err != nil {
		return err
	}
	if err := json.Unmarshal(data, &t.PublicProfileFields); err != nil {
		return err
	}
	return nil
}
func (t *UserOperation_User_OptionalProfile) GetPrivateProfileFields() PrivateProfileFields {
	if t == nil {
		t = &UserOperation_User_OptionalProfile{}
	}
	return t.PrivateProfileFields
}
func (t *UserOperation_User_OptionalProfile) GetPublicProfileFields() PublicProfileFields {
	if t == nil {
		t = &UserOperation_User_OptionalProfile{}
	}
	return t.PublicProfileFields
}

type UserOperation_User_Profile struct {
	PrivateProfileFields "json:\"-\""
	PublicProfileFields  "json:\"-\""
}

func (t *UserOperation_User_Profile) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	data, err := dec.ReadValue()
	if err != nil {
		return err
	}
	if err := json.Unmarshal(data, &t.PrivateProfileFields); err != nil {
		return err
	}
	if err := json.Unmarshal(data, &t.PublicProfileFields); err != nil {
		return err
	}
	return nil
}
func (t *UserOperation_User_Profile) GetPrivateProfileFields() PrivateProfileFields {
	if t == nil {
		t = &UserOperation_User_Profile{}
	}
	return t.PrivateProfileFields
}
func (t *UserOperation_User_Profile) GetPublicProfileFields() PublicProfileFields {
	if t == nil {
		t = &UserOperation_User_Profile{}
	}
	return t.PublicProfileFields
}

type UserOperation_User_Profile2 struct {
	PrivateProfile *struct {
		Age *int "json:\"age\""
	} "json:\"-\""
	PublicProfile *struct {
		Status Status "json:\"status\""
	} "json:\"-\""
	Typename string "json:\"__typename\""
}

func (t *UserOperation_User_Profile2) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	data, err := dec.ReadValue()
	if err != nil {
		return err
	}
	type plain UserOperation_User_Profile2
	if err := json.Unmarshal(data, (*plain)(t)); err != nil {
		return err
	}
	switch t.Typename {
	case "PrivateProfile":
		if err := json.Unmarshal(data, &t.PrivateProfile); err != nil {
			return err
		}
	case "PublicProfile":
		if err := json.Unmarshal(data, &t.PublicProfile); err != nil {
			return err
		}
	}
	return nil
}
func (t *UserOperation_User_Profile2) GetPrivateProfile() *struct {
	Age *int "json:\"age\""
} {
	if t == nil {
		t = &UserOperation_User_Profile2{}
	}
	return t.PrivateProfile
}
func (t *UserOperation_User_Profile2) GetPublicProfile() *struct {
	Status Status "json:\"status\""
} {
	if t == nil {
		t = &UserOperation_User_Profile2{}
	}
	return t.PublicProfile
}
func (t *UserOperation_User_Profile2) GetTypename() string {
	if t == nil {
		t = &UserOperation_User_Profile2{}
	}
	return t.Typename
}

const UpdateUserDocument = `mutation UpdateUser($input: UpdateUserInput!) { updateUser(input: $input) { user { name settings { theme notifications } } } }`
const UserOperationDocument = `query UserOperation($articleId: ID!, $metadataId: ID!, $size: Int = 100, $userId: ID, $userStatus: Status) { user(id: $userId, status: $userStatus) { __typename name email name2: name smallPic: profilePic(size: 50) largePic: profilePic(size: 500) defaultPic: profilePic(size: $size) profile { ...PublicProfileFields ...PrivateProfileFields } profile2: profile { __typename ... on PublicProfile { status } ... on PrivateProfile { age } } optionalProfile { ...PublicProfileFields ...PrivateProfileFields } address { street ...PublicAddressFields ...PrivateAddressFields } optionalAddress { __typename street ... on PublicAddress { street public } ... on PrivateAddress { street private } } ...UserFragment1 ...UserFragment2 ... on User { name ...UserFragment2 } } optionalUser { name email } article(id: $articleId) { id title tags optionalTags comments { id text } optionalComments { id text } rating optionalRating nullableElementsList fullyNullableList statuses optionalStatuses addresses { street ...PublicAddressFields ...PrivateAddressFields } optionalAddresses { __typename street ... on PublicAddress { public } ... on PrivateAddress { private } } profiles { ...PublicProfileFields ...PrivateProfileFields } optionalProfiles { __typename ... on PublicProfile { status } ... on PrivateProfile { age } } matrix optionalMatrix } metadata(id: $metadataId) { id data properties level } } fragment PublicProfileFields on PublicProfile { id status } fragment PrivateProfileFields on PrivateProfile { id age } fragment PublicAddressFields on PublicAddress { id street public } fragment PrivateAddressFields on PrivateAddress { id street private } fragment UserFragment1 on User { __typename name name ... on User { name } profile { __typename ... on PublicProfile { status } ... on PrivateProfile { age } } } fragment UserFragment2 on User { name }`
const CountDocument = `subscription Count($target: Int!) { count(target: $target) }`
