// Code generated by github.com/Yamashou/gqlgenc, DO NOT EDIT.

package domain

import (
	"encoding/json/jsontext"
	json "encoding/json/v2"
)

type PrivateAddressFields struct {
	ID      string "json:\"id,omitempty,omitzero\""
	Private bool   "json:\"private,omitempty,omitzero\""
	Street  string "json:\"street,omitempty,omitzero\""
}

type PrivateProfileFields struct {
	Age *int   "json:\"age\""
	ID  string "json:\"id,omitempty,omitzero\""
}

type PublicAddressFields struct {
	ID     string "json:\"id,omitempty,omitzero\""
	Public bool   "json:\"public,omitempty,omitzero\""
	Street string "json:\"street,omitempty,omitzero\""
}

type PublicProfileFields struct {
	ID     string "json:\"id,omitempty,omitzero\""
	Status Status "json:\"status,omitempty,omitzero\""
}

type UpdateUser struct {
	UpdateUser UpdateUser_UpdateUser "json:\"updateUser,omitempty,omitzero\""
}

func (t *UpdateUser) UnmarshalJSON(data []byte) error {
	var raw map[string]jsontext.Value
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	type Alias UpdateUser
	var aux Alias
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	*t = UpdateUser(aux)
	if value, ok := raw["updateUser"]; ok {
		if err := json.Unmarshal(value, &t.UpdateUser); err != nil {
			return err
		}
	}
	return nil
}
func (t *UpdateUser) GetUpdateUser() UpdateUser_UpdateUser {
	if t == nil {
		t = &UpdateUser{}
	}
	return t.UpdateUser
}

type UpdateUser_UpdateUser struct {
	User UpdateUser_UpdateUser_User "json:\"user,omitempty,omitzero\""
}

func (t *UpdateUser_UpdateUser) UnmarshalJSON(data []byte) error {
	var raw map[string]jsontext.Value
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	type Alias UpdateUser_UpdateUser
	var aux Alias
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	*t = UpdateUser_UpdateUser(aux)
	if value, ok := raw["user"]; ok {
		if err := json.Unmarshal(value, &t.User); err != nil {
			return err
		}
	}
	return nil
}

type UpdateUser_UpdateUser_User struct {
	Name     string                               "json:\"name,omitempty,omitzero\""
	Settings *UpdateUser_UpdateUser_User_Settings "json:\"settings\""
}

func (t *UpdateUser_UpdateUser_User) UnmarshalJSON(data []byte) error {
	var raw map[string]jsontext.Value
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	type Alias UpdateUser_UpdateUser_User
	var aux Alias
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	*t = UpdateUser_UpdateUser_User(aux)
	if value, ok := raw["name"]; ok {
		if err := json.Unmarshal(value, &t.Name); err != nil {
			return err
		}
	}
	if value, ok := raw["settings"]; ok {
		if err := json.Unmarshal(value, &t.Settings); err != nil {
			return err
		}
	}
	return nil
}

type UpdateUser_UpdateUser_User_Settings struct {
	Notifications bool   "json:\"notifications,omitempty,omitzero\""
	Theme         string "json:\"theme,omitempty,omitzero\""
}

func (t *UpdateUser_UpdateUser_User_Settings) UnmarshalJSON(data []byte) error {
	var raw map[string]jsontext.Value
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	type Alias UpdateUser_UpdateUser_User_Settings
	var aux Alias
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	*t = UpdateUser_UpdateUser_User_Settings(aux)
	if value, ok := raw["notifications"]; ok {
		if err := json.Unmarshal(value, &t.Notifications); err != nil {
			return err
		}
	}
	if value, ok := raw["theme"]; ok {
		if err := json.Unmarshal(value, &t.Theme); err != nil {
			return err
		}
	}
	return nil
}

type UserFragment1 struct {
	User struct {
		Name string "json:\"name,omitempty,omitzero\""
	} "json:\"-\""
	Name    string                "json:\"name,omitempty,omitzero\""
	Profile UserFragment1_Profile "json:\"profile,omitempty,omitzero\""
}

type UserFragment1_Profile struct {
	PrivateProfile struct {
		Age *int "json:\"age\""
	} "json:\"-\""
	PublicProfile struct {
		Status Status "json:\"status,omitempty,omitzero\""
	} "json:\"-\""
}

func (t *UserFragment1_Profile) UnmarshalJSON(data []byte) error {
	var raw map[string]jsontext.Value
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	type Alias UserFragment1_Profile
	var aux Alias
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	*t = UserFragment1_Profile(aux)
	if err := json.Unmarshal(data, &t.PrivateProfile); err != nil {
		return err
	}
	if value, ok := raw["age"]; ok {
		if err := json.Unmarshal(value, &t.PrivateProfile.Age); err != nil {
			return err
		}
	}
	if err := json.Unmarshal(data, &t.PublicProfile); err != nil {
		return err
	}
	if value, ok := raw["status"]; ok {
		if err := json.Unmarshal(value, &t.PublicProfile.Status); err != nil {
			return err
		}
	}
	return nil
}

type UserFragment2 struct {
	Name string "json:\"name,omitempty,omitzero\""
}

func (t *UserFragment2) UnmarshalJSON(data []byte) error {
	var raw map[string]jsontext.Value
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	type Alias UserFragment2
	var aux Alias
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	*t = UserFragment2(aux)
	if value, ok := raw["name"]; ok {
		if err := json.Unmarshal(value, &t.Name); err != nil {
			return err
		}
	}
	return nil
}

type UserOperation struct {
	Article      *UserOperation_Article      "json:\"article\""
	Metadata     *UserOperation_Metadata     "json:\"metadata\""
	OptionalUser *UserOperation_OptionalUser "json:\"optionalUser\""
	User         UserOperation_User          "json:\"user,omitempty,omitzero\""
}

func (t *UserOperation) UnmarshalJSON(data []byte) error {
	var raw map[string]jsontext.Value
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	type Alias UserOperation
	var aux Alias
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	*t = UserOperation(aux)
	if value, ok := raw["article"]; ok {
		if err := json.Unmarshal(value, &t.Article); err != nil {
			return err
		}
	}
	if value, ok := raw["metadata"]; ok {
		if err := json.Unmarshal(value, &t.Metadata); err != nil {
			return err
		}
	}
	if value, ok := raw["optionalUser"]; ok {
		if err := json.Unmarshal(value, &t.OptionalUser); err != nil {
			return err
		}
	}
	if value, ok := raw["user"]; ok {
		if err := json.Unmarshal(value, &t.User); err != nil {
			return err
		}
	}
	return nil
}
func (t *UserOperation) GetArticle() *UserOperation_Article {
	if t == nil {
		t = &UserOperation{}
	}
	return t.Article
}
func (t *UserOperation) GetMetadata() *UserOperation_Metadata {
	if t == nil {
		t = &UserOperation{}
	}
	return t.Metadata
}
func (t *UserOperation) GetOptionalUser() *UserOperation_OptionalUser {
	if t == nil {
		t = &UserOperation{}
	}
	return t.OptionalUser
}
func (t *UserOperation) GetUser() UserOperation_User {
	if t == nil {
		t = &UserOperation{}
	}
	return t.User
}

type UserOperation_Article struct {
	Addresses            []*UserOperation_Article_Addresses          "json:\"addresses,omitempty,omitzero\""
	Comments             []*UserOperation_Article_Comments           "json:\"comments,omitempty,omitzero\""
	FullyNullableList    *[]*string                                  "json:\"fullyNullableList\""
	ID                   string                                      "json:\"id,omitempty,omitzero\""
	Matrix               [][]string                                  "json:\"matrix,omitempty,omitzero\""
	NullableElementsList []*string                                   "json:\"nullableElementsList,omitempty,omitzero\""
	OptionalAddresses    *[]*UserOperation_Article_OptionalAddresses "json:\"optionalAddresses\""
	OptionalComments     *[]*UserOperation_Article_OptionalComments  "json:\"optionalComments\""
	OptionalMatrix       *[][]string                                 "json:\"optionalMatrix\""
	OptionalProfiles     *[]*UserOperation_Article_OptionalProfiles  "json:\"optionalProfiles\""
	OptionalRating       *float64                                    "json:\"optionalRating\""
	OptionalStatuses     *[]Status                                   "json:\"optionalStatuses\""
	OptionalTags         *[]string                                   "json:\"optionalTags\""
	Profiles             []*UserOperation_Article_Profiles           "json:\"profiles,omitempty,omitzero\""
	Rating               float64                                     "json:\"rating,omitempty,omitzero\""
	Statuses             []Status                                    "json:\"statuses,omitempty,omitzero\""
	Tags                 []string                                    "json:\"tags,omitempty,omitzero\""
	Title                string                                      "json:\"title,omitempty,omitzero\""
}

func (t *UserOperation_Article) UnmarshalJSON(data []byte) error {
	var raw map[string]jsontext.Value
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	type Alias UserOperation_Article
	var aux Alias
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	*t = UserOperation_Article(aux)
	if value, ok := raw["addresses"]; ok {
		if err := json.Unmarshal(value, &t.Addresses); err != nil {
			return err
		}
	}
	if value, ok := raw["comments"]; ok {
		if err := json.Unmarshal(value, &t.Comments); err != nil {
			return err
		}
	}
	if value, ok := raw["fullyNullableList"]; ok {
		if err := json.Unmarshal(value, &t.FullyNullableList); err != nil {
			return err
		}
	}
	if value, ok := raw["id"]; ok {
		if err := json.Unmarshal(value, &t.ID); err != nil {
			return err
		}
	}
	if value, ok := raw["matrix"]; ok {
		if err := json.Unmarshal(value, &t.Matrix); err != nil {
			return err
		}
	}
	if value, ok := raw["nullableElementsList"]; ok {
		if err := json.Unmarshal(value, &t.NullableElementsList); err != nil {
			return err
		}
	}
	if value, ok := raw["optionalAddresses"]; ok {
		if err := json.Unmarshal(value, &t.OptionalAddresses); err != nil {
			return err
		}
	}
	if value, ok := raw["optionalComments"]; ok {
		if err := json.Unmarshal(value, &t.OptionalComments); err != nil {
			return err
		}
	}
	if value, ok := raw["optionalMatrix"]; ok {
		if err := json.Unmarshal(value, &t.OptionalMatrix); err != nil {
			return err
		}
	}
	if value, ok := raw["optionalProfiles"]; ok {
		if err := json.Unmarshal(value, &t.OptionalProfiles); err != nil {
			return err
		}
	}
	if value, ok := raw["optionalRating"]; ok {
		if err := json.Unmarshal(value, &t.OptionalRating); err != nil {
			return err
		}
	}
	if value, ok := raw["optionalStatuses"]; ok {
		if err := json.Unmarshal(value, &t.OptionalStatuses); err != nil {
			return err
		}
	}
	if value, ok := raw["optionalTags"]; ok {
		if err := json.Unmarshal(value, &t.OptionalTags); err != nil {
			return err
		}
	}
	if value, ok := raw["profiles"]; ok {
		if err := json.Unmarshal(value, &t.Profiles); err != nil {
			return err
		}
	}
	if value, ok := raw["rating"]; ok {
		if err := json.Unmarshal(value, &t.Rating); err != nil {
			return err
		}
	}
	if value, ok := raw["statuses"]; ok {
		if err := json.Unmarshal(value, &t.Statuses); err != nil {
			return err
		}
	}
	if value, ok := raw["tags"]; ok {
		if err := json.Unmarshal(value, &t.Tags); err != nil {
			return err
		}
	}
	if value, ok := raw["title"]; ok {
		if err := json.Unmarshal(value, &t.Title); err != nil {
			return err
		}
	}
	return nil
}

type UserOperation_Article_Addresses struct {
	PrivateAddressFields "json:\"-\""
	PublicAddressFields  "json:\"-\""
	Street               string "json:\"street,omitempty,omitzero\""
}

func (t *UserOperation_Article_Addresses) UnmarshalJSON(data []byte) error {
	var raw map[string]jsontext.Value
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	type Alias UserOperation_Article_Addresses
	var aux Alias
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	*t = UserOperation_Article_Addresses(aux)
	if value, ok := raw["street"]; ok {
		if err := json.Unmarshal(value, &t.Street); err != nil {
			return err
		}
	}
	if err := json.Unmarshal(data, &t.PrivateAddressFields); err != nil {
		return err
	}
	if value, ok := raw["id"]; ok {
		if err := json.Unmarshal(value, &t.PrivateAddressFields.ID); err != nil {
			return err
		}
	}
	if value, ok := raw["private"]; ok {
		if err := json.Unmarshal(value, &t.PrivateAddressFields.Private); err != nil {
			return err
		}
	}
	if value, ok := raw["street"]; ok {
		if err := json.Unmarshal(value, &t.PrivateAddressFields.Street); err != nil {
			return err
		}
	}
	if err := json.Unmarshal(data, &t.PublicAddressFields); err != nil {
		return err
	}
	if value, ok := raw["id"]; ok {
		if err := json.Unmarshal(value, &t.PublicAddressFields.ID); err != nil {
			return err
		}
	}
	if value, ok := raw["public"]; ok {
		if err := json.Unmarshal(value, &t.PublicAddressFields.Public); err != nil {
			return err
		}
	}
	if value, ok := raw["street"]; ok {
		if err := json.Unmarshal(value, &t.PublicAddressFields.Street); err != nil {
			return err
		}
	}
	return nil
}

type UserOperation_Article_Comments struct {
	ID   string "json:\"id,omitempty,omitzero\""
	Text string "json:\"text,omitempty,omitzero\""
}

func (t *UserOperation_Article_Comments) UnmarshalJSON(data []byte) error {
	var raw map[string]jsontext.Value
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	type Alias UserOperation_Article_Comments
	var aux Alias
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	*t = UserOperation_Article_Comments(aux)
	if value, ok := raw["id"]; ok {
		if err := json.Unmarshal(value, &t.ID); err != nil {
			return err
		}
	}
	if value, ok := raw["text"]; ok {
		if err := json.Unmarshal(value, &t.Text); err != nil {
			return err
		}
	}
	return nil
}

type UserOperation_Article_OptionalAddresses struct {
	PrivateAddress struct {
		Private bool "json:\"private,omitempty,omitzero\""
	} "json:\"-\""
	PublicAddress struct {
		Public bool "json:\"public,omitempty,omitzero\""
	} "json:\"-\""
	Street string "json:\"street,omitempty,omitzero\""
}

func (t *UserOperation_Article_OptionalAddresses) UnmarshalJSON(data []byte) error {
	var raw map[string]jsontext.Value
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	type Alias UserOperation_Article_OptionalAddresses
	var aux Alias
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	*t = UserOperation_Article_OptionalAddresses(aux)
	if value, ok := raw["street"]; ok {
		if err := json.Unmarshal(value, &t.Street); err != nil {
			return err
		}
	}
	if err := json.Unmarshal(data, &t.PrivateAddress); err != nil {
		return err
	}
	if value, ok := raw["private"]; ok {
		if err := json.Unmarshal(value, &t.PrivateAddress.Private); err != nil {
			return err
		}
	}
	if err := json.Unmarshal(data, &t.PublicAddress); err != nil {
		return err
	}
	if value, ok := raw["public"]; ok {
		if err := json.Unmarshal(value, &t.PublicAddress.Public); err != nil {
			return err
		}
	}
	return nil
}

type UserOperation_Article_OptionalComments struct {
	ID   string "json:\"id,omitempty,omitzero\""
	Text string "json:\"text,omitempty,omitzero\""
}

func (t *UserOperation_Article_OptionalComments) UnmarshalJSON(data []byte) error {
	var raw map[string]jsontext.Value
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	type Alias UserOperation_Article_OptionalComments
	var aux Alias
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	*t = UserOperation_Article_OptionalComments(aux)
	if value, ok := raw["id"]; ok {
		if err := json.Unmarshal(value, &t.ID); err != nil {
			return err
		}
	}
	if value, ok := raw["text"]; ok {
		if err := json.Unmarshal(value, &t.Text); err != nil {
			return err
		}
	}
	return nil
}

type UserOperation_Article_OptionalProfiles struct {
	PrivateProfile struct {
		Age *int "json:\"age\""
	} "json:\"-\""
	PublicProfile struct {
		Status Status "json:\"status,omitempty,omitzero\""
	} "json:\"-\""
}

func (t *UserOperation_Article_OptionalProfiles) UnmarshalJSON(data []byte) error {
	var raw map[string]jsontext.Value
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	type Alias UserOperation_Article_OptionalProfiles
	var aux Alias
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	*t = UserOperation_Article_OptionalProfiles(aux)
	if err := json.Unmarshal(data, &t.PrivateProfile); err != nil {
		return err
	}
	if value, ok := raw["age"]; ok {
		if err := json.Unmarshal(value, &t.PrivateProfile.Age); err != nil {
			return err
		}
	}
	if err := json.Unmarshal(data, &t.PublicProfile); err != nil {
		return err
	}
	if value, ok := raw["status"]; ok {
		if err := json.Unmarshal(value, &t.PublicProfile.Status); err != nil {
			return err
		}
	}
	return nil
}

type UserOperation_Article_Profiles struct {
	PrivateProfileFields "json:\"-\""
	PublicProfileFields  "json:\"-\""
}

func (t *UserOperation_Article_Profiles) UnmarshalJSON(data []byte) error {
	var raw map[string]jsontext.Value
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	type Alias UserOperation_Article_Profiles
	var aux Alias
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	*t = UserOperation_Article_Profiles(aux)
	if err := json.Unmarshal(data, &t.PrivateProfileFields); err != nil {
		return err
	}
	if value, ok := raw["age"]; ok {
		if err := json.Unmarshal(value, &t.PrivateProfileFields.Age); err != nil {
			return err
		}
	}
	if value, ok := raw["id"]; ok {
		if err := json.Unmarshal(value, &t.PrivateProfileFields.ID); err != nil {
			return err
		}
	}
	if err := json.Unmarshal(data, &t.PublicProfileFields); err != nil {
		return err
	}
	if value, ok := raw["id"]; ok {
		if err := json.Unmarshal(value, &t.PublicProfileFields.ID); err != nil {
			return err
		}
	}
	if value, ok := raw["status"]; ok {
		if err := json.Unmarshal(value, &t.PublicProfileFields.Status); err != nil {
			return err
		}
	}
	return nil
}

type UserOperation_Metadata struct {
	Data *string "json:\"data\""
	ID   string  "json:\"id,omitempty,omitzero\""
}

func (t *UserOperation_Metadata) UnmarshalJSON(data []byte) error {
	var raw map[string]jsontext.Value
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	type Alias UserOperation_Metadata
	var aux Alias
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	*t = UserOperation_Metadata(aux)
	if value, ok := raw["data"]; ok {
		if err := json.Unmarshal(value, &t.Data); err != nil {
			return err
		}
	}
	if value, ok := raw["id"]; ok {
		if err := json.Unmarshal(value, &t.ID); err != nil {
			return err
		}
	}
	return nil
}

type UserOperation_OptionalUser struct {
	Name string "json:\"name,omitempty,omitzero\""
}

func (t *UserOperation_OptionalUser) UnmarshalJSON(data []byte) error {
	var raw map[string]jsontext.Value
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	type Alias UserOperation_OptionalUser
	var aux Alias
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	*t = UserOperation_OptionalUser(aux)
	if value, ok := raw["name"]; ok {
		if err := json.Unmarshal(value, &t.Name); err != nil {
			return err
		}
	}
	return nil
}

type UserOperation_User struct {
	User struct {
		UserFragment2 "json:\"-\""
		Name          string "json:\"name,omitempty,omitzero\""
	} "json:\"-\""
	UserFragment1   "json:\"-\""
	UserFragment2   "json:\"-\""
	Address         UserOperation_User_Address          "json:\"address,omitempty,omitzero\""
	DefaultPic      string                              "json:\"defaultPic,omitempty,omitzero\""
	LargePic        string                              "json:\"largePic,omitempty,omitzero\""
	Name            string                              "json:\"name,omitempty,omitzero\""
	Name2           string                              "json:\"name2,omitempty,omitzero\""
	OptionalAddress *UserOperation_User_OptionalAddress "json:\"optionalAddress\""
	OptionalProfile *UserOperation_User_OptionalProfile "json:\"optionalProfile\""
	Profile         UserOperation_User_Profile          "json:\"profile,omitempty,omitzero\""
	Profile2        UserOperation_User_Profile2         "json:\"profile2,omitempty,omitzero\""
	SmallPic        string                              "json:\"smallPic,omitempty,omitzero\""
}

func (t *UserOperation_User) UnmarshalJSON(data []byte) error {
	var raw map[string]jsontext.Value
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	type Alias UserOperation_User
	var aux Alias
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	*t = UserOperation_User(aux)
	if value, ok := raw["address"]; ok {
		if err := json.Unmarshal(value, &t.Address); err != nil {
			return err
		}
	}
	if value, ok := raw["defaultPic"]; ok {
		if err := json.Unmarshal(value, &t.DefaultPic); err != nil {
			return err
		}
	}
	if value, ok := raw["largePic"]; ok {
		if err := json.Unmarshal(value, &t.LargePic); err != nil {
			return err
		}
	}
	if value, ok := raw["name"]; ok {
		if err := json.Unmarshal(value, &t.Name); err != nil {
			return err
		}
	}
	if value, ok := raw["name2"]; ok {
		if err := json.Unmarshal(value, &t.Name2); err != nil {
			return err
		}
	}
	if value, ok := raw["optionalAddress"]; ok {
		if err := json.Unmarshal(value, &t.OptionalAddress); err != nil {
			return err
		}
	}
	if value, ok := raw["optionalProfile"]; ok {
		if err := json.Unmarshal(value, &t.OptionalProfile); err != nil {
			return err
		}
	}
	if value, ok := raw["profile"]; ok {
		if err := json.Unmarshal(value, &t.Profile); err != nil {
			return err
		}
	}
	if value, ok := raw["profile2"]; ok {
		if err := json.Unmarshal(value, &t.Profile2); err != nil {
			return err
		}
	}
	if value, ok := raw["smallPic"]; ok {
		if err := json.Unmarshal(value, &t.SmallPic); err != nil {
			return err
		}
	}
	if err := json.Unmarshal(data, &t.User); err != nil {
		return err
	}
	if value, ok := raw["name"]; ok {
		if err := json.Unmarshal(value, &t.User.Name); err != nil {
			return err
		}
	}
	if err := json.Unmarshal(data, &t.User.UserFragment2); err != nil {
		return err
	}
	if err := json.Unmarshal(data, &t.UserFragment1); err != nil {
		return err
	}
	if value, ok := raw["name"]; ok {
		if err := json.Unmarshal(value, &t.UserFragment1.Name); err != nil {
			return err
		}
	}
	if value, ok := raw["profile"]; ok {
		if err := json.Unmarshal(value, &t.UserFragment1.Profile); err != nil {
			return err
		}
	}
	if err := json.Unmarshal(data, &t.UserFragment1.User); err != nil {
		return err
	}
	if value, ok := raw["name"]; ok {
		if err := json.Unmarshal(value, &t.UserFragment1.User.Name); err != nil {
			return err
		}
	}
	if err := json.Unmarshal(data, &t.UserFragment2); err != nil {
		return err
	}
	if value, ok := raw["name"]; ok {
		if err := json.Unmarshal(value, &t.UserFragment2.Name); err != nil {
			return err
		}
	}
	return nil
}

type UserOperation_User_Address struct {
	PrivateAddressFields "json:\"-\""
	PublicAddressFields  "json:\"-\""
	Street               string "json:\"street,omitempty,omitzero\""
}

func (t *UserOperation_User_Address) UnmarshalJSON(data []byte) error {
	var raw map[string]jsontext.Value
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	type Alias UserOperation_User_Address
	var aux Alias
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	*t = UserOperation_User_Address(aux)
	if value, ok := raw["street"]; ok {
		if err := json.Unmarshal(value, &t.Street); err != nil {
			return err
		}
	}
	if err := json.Unmarshal(data, &t.PrivateAddressFields); err != nil {
		return err
	}
	if value, ok := raw["id"]; ok {
		if err := json.Unmarshal(value, &t.PrivateAddressFields.ID); err != nil {
			return err
		}
	}
	if value, ok := raw["private"]; ok {
		if err := json.Unmarshal(value, &t.PrivateAddressFields.Private); err != nil {
			return err
		}
	}
	if value, ok := raw["street"]; ok {
		if err := json.Unmarshal(value, &t.PrivateAddressFields.Street); err != nil {
			return err
		}
	}
	if err := json.Unmarshal(data, &t.PublicAddressFields); err != nil {
		return err
	}
	if value, ok := raw["id"]; ok {
		if err := json.Unmarshal(value, &t.PublicAddressFields.ID); err != nil {
			return err
		}
	}
	if value, ok := raw["public"]; ok {
		if err := json.Unmarshal(value, &t.PublicAddressFields.Public); err != nil {
			return err
		}
	}
	if value, ok := raw["street"]; ok {
		if err := json.Unmarshal(value, &t.PublicAddressFields.Street); err != nil {
			return err
		}
	}
	return nil
}

type UserOperation_User_OptionalAddress struct {
	PrivateAddress struct {
		Private bool   "json:\"private,omitempty,omitzero\""
		Street  string "json:\"street,omitempty,omitzero\""
	} "json:\"-\""
	PublicAddress struct {
		Public bool   "json:\"public,omitempty,omitzero\""
		Street string "json:\"street,omitempty,omitzero\""
	} "json:\"-\""
	Street string "json:\"street,omitempty,omitzero\""
}

func (t *UserOperation_User_OptionalAddress) UnmarshalJSON(data []byte) error {
	var raw map[string]jsontext.Value
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	type Alias UserOperation_User_OptionalAddress
	var aux Alias
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	*t = UserOperation_User_OptionalAddress(aux)
	if value, ok := raw["street"]; ok {
		if err := json.Unmarshal(value, &t.Street); err != nil {
			return err
		}
	}
	if err := json.Unmarshal(data, &t.PrivateAddress); err != nil {
		return err
	}
	if value, ok := raw["private"]; ok {
		if err := json.Unmarshal(value, &t.PrivateAddress.Private); err != nil {
			return err
		}
	}
	if value, ok := raw["street"]; ok {
		if err := json.Unmarshal(value, &t.PrivateAddress.Street); err != nil {
			return err
		}
	}
	if err := json.Unmarshal(data, &t.PublicAddress); err != nil {
		return err
	}
	if value, ok := raw["public"]; ok {
		if err := json.Unmarshal(value, &t.PublicAddress.Public); err != nil {
			return err
		}
	}
	if value, ok := raw["street"]; ok {
		if err := json.Unmarshal(value, &t.PublicAddress.Street); err != nil {
			return err
		}
	}
	return nil
}

type UserOperation_User_OptionalProfile struct {
	PrivateProfileFields "json:\"-\""
	PublicProfileFields  "json:\"-\""
}

func (t *UserOperation_User_OptionalProfile) UnmarshalJSON(data []byte) error {
	var raw map[string]jsontext.Value
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	type Alias UserOperation_User_OptionalProfile
	var aux Alias
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	*t = UserOperation_User_OptionalProfile(aux)
	if err := json.Unmarshal(data, &t.PrivateProfileFields); err != nil {
		return err
	}
	if value, ok := raw["age"]; ok {
		if err := json.Unmarshal(value, &t.PrivateProfileFields.Age); err != nil {
			return err
		}
	}
	if value, ok := raw["id"]; ok {
		if err := json.Unmarshal(value, &t.PrivateProfileFields.ID); err != nil {
			return err
		}
	}
	if err := json.Unmarshal(data, &t.PublicProfileFields); err != nil {
		return err
	}
	if value, ok := raw["id"]; ok {
		if err := json.Unmarshal(value, &t.PublicProfileFields.ID); err != nil {
			return err
		}
	}
	if value, ok := raw["status"]; ok {
		if err := json.Unmarshal(value, &t.PublicProfileFields.Status); err != nil {
			return err
		}
	}
	return nil
}

type UserOperation_User_Profile struct {
	PrivateProfileFields "json:\"-\""
	PublicProfileFields  "json:\"-\""
}

func (t *UserOperation_User_Profile) UnmarshalJSON(data []byte) error {
	var raw map[string]jsontext.Value
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	type Alias UserOperation_User_Profile
	var aux Alias
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	*t = UserOperation_User_Profile(aux)
	if err := json.Unmarshal(data, &t.PrivateProfileFields); err != nil {
		return err
	}
	if value, ok := raw["age"]; ok {
		if err := json.Unmarshal(value, &t.PrivateProfileFields.Age); err != nil {
			return err
		}
	}
	if value, ok := raw["id"]; ok {
		if err := json.Unmarshal(value, &t.PrivateProfileFields.ID); err != nil {
			return err
		}
	}
	if err := json.Unmarshal(data, &t.PublicProfileFields); err != nil {
		return err
	}
	if value, ok := raw["id"]; ok {
		if err := json.Unmarshal(value, &t.PublicProfileFields.ID); err != nil {
			return err
		}
	}
	if value, ok := raw["status"]; ok {
		if err := json.Unmarshal(value, &t.PublicProfileFields.Status); err != nil {
			return err
		}
	}
	return nil
}

type UserOperation_User_Profile2 struct {
	PrivateProfile struct {
		Age *int "json:\"age\""
	} "json:\"-\""
	PublicProfile struct {
		Status Status "json:\"status,omitempty,omitzero\""
	} "json:\"-\""
}

func (t *UserOperation_User_Profile2) UnmarshalJSON(data []byte) error {
	var raw map[string]jsontext.Value
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	type Alias UserOperation_User_Profile2
	var aux Alias
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	*t = UserOperation_User_Profile2(aux)
	if err := json.Unmarshal(data, &t.PrivateProfile); err != nil {
		return err
	}
	if value, ok := raw["age"]; ok {
		if err := json.Unmarshal(value, &t.PrivateProfile.Age); err != nil {
			return err
		}
	}
	if err := json.Unmarshal(data, &t.PublicProfile); err != nil {
		return err
	}
	if value, ok := raw["status"]; ok {
		if err := json.Unmarshal(value, &t.PublicProfile.Status); err != nil {
			return err
		}
	}
	return nil
}

const UpdateUserDocument = `mutation UpdateUser ($input: UpdateUserInput!) {
	updateUser(input: $input) {
		user {
			name
			settings {
				theme
				notifications
			}
		}
	}
}
`
const UserOperationDocument = `query UserOperation ($articleId: ID!, $metadataId: ID!, $size: Int = 100) {
	user {
		name
		name2: name
		smallPic: profilePic(size: 50)
		largePic: profilePic(size: 500)
		defaultPic: profilePic(size: $size)
		profile {
			... PublicProfileFields
			... PrivateProfileFields
		}
		profile2: profile {
			... on PublicProfile {
				status
			}
			... on PrivateProfile {
				age
			}
		}
		optionalProfile {
			... PublicProfileFields
			... PrivateProfileFields
		}
		address {
			street
			... PublicAddressFields
			... PrivateAddressFields
		}
		optionalAddress {
			street
			... on PublicAddress {
				street
				public
			}
			... on PrivateAddress {
				street
				private
			}
		}
		... UserFragment1
		... UserFragment2
		... on User {
			name
			... UserFragment2
		}
	}
	optionalUser {
		name
	}
	article(id: $articleId) {
		id
		title
		tags
		optionalTags
		comments {
			id
			text
		}
		optionalComments {
			id
			text
		}
		rating
		optionalRating
		nullableElementsList
		fullyNullableList
		statuses
		optionalStatuses
		addresses {
			street
			... PublicAddressFields
			... PrivateAddressFields
		}
		optionalAddresses {
			street
			... on PublicAddress {
				public
			}
			... on PrivateAddress {
				private
			}
		}
		profiles {
			... PublicProfileFields
			... PrivateProfileFields
		}
		optionalProfiles {
			... on PublicProfile {
				status
			}
			... on PrivateProfile {
				age
			}
		}
		matrix
		optionalMatrix
	}
	metadata(id: $metadataId) {
		id
		data
	}
}
fragment PublicProfileFields on PublicProfile {
	id
	status
}
fragment PrivateProfileFields on PrivateProfile {
	id
	age
}
fragment PublicAddressFields on PublicAddress {
	id
	street
	public
}
fragment PrivateAddressFields on PrivateAddress {
	id
	street
	private
}
fragment UserFragment1 on User {
	name
	name
	... on User {
		name
	}
	profile {
		... on PublicProfile {
			status
		}
		... on PrivateProfile {
			age
		}
	}
}
fragment UserFragment2 on User {
	name
}
`

var DocumentOperationNames = map[string]string{
	UpdateUserDocument:    "UpdateUser",
	UserOperationDocument: "UserOperation",
}
