// Code generated by github.com/gqlgo/gqlgenc, DO NOT EDIT.

package generated

import (
	"context"

	"github.com/gqlgo/gqlgenc/clientv2"
)

type Client struct {
	Client *clientv2.Client
}

func NewClient(cli clientv2.HttpClient, baseURL string, options *clientv2.Options, interceptors ...clientv2.RequestInterceptor) *Client {
	return &Client{Client: clientv2.NewClient(cli, baseURL, options, interceptors...)}
}

type ListUsers_Users struct {
	Active bool   "json:\"active\" graphql:\"active\""
	Age    *int   "json:\"age,omitempty\" graphql:\"age\""
	ID     string "json:\"id\" graphql:\"id\""
	Name   string "json:\"name\" graphql:\"name\""
}

func (t *ListUsers_Users) GetActive() bool {
	if t == nil {
		t = &ListUsers_Users{}
	}
	return t.Active
}
func (t *ListUsers_Users) GetAge() *int {
	if t == nil {
		t = &ListUsers_Users{}
	}
	return t.Age
}
func (t *ListUsers_Users) GetID() string {
	if t == nil {
		t = &ListUsers_Users{}
	}
	return t.ID
}
func (t *ListUsers_Users) GetName() string {
	if t == nil {
		t = &ListUsers_Users{}
	}
	return t.Name
}

type ListUsers struct {
	Users []*ListUsers_Users "json:\"users\" graphql:\"users\""
}

func (t *ListUsers) GetUsers() []*ListUsers_Users {
	if t == nil {
		t = &ListUsers{}
	}
	return t.Users
}

const ListUsersDocument = `query ListUsers ($filter: UserFilter) {
	users(filter: $filter) @dummy_list_size(size: 2) {
		id @dummy_custom(value: "user-1")
		name @dummy_custom(value: "Alice")
		age @dummy_int(min: 25, max: 25)
		active @dummy_bool
	}
}
`

func (c *Client) ListUsers(ctx context.Context, filter *UserFilter, interceptors ...clientv2.RequestInterceptor) (*ListUsers, error) {
	vars := map[string]any{
		"filter": filter,
	}

	var res ListUsers
	if err := c.Client.Post(ctx, "ListUsers", ListUsersDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

var DocumentOperationNames = map[string]string{
	ListUsersDocument: "ListUsers",
}
