// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package generated

import (
	"github.com/99designs/gqlgen/graphql"
)

type Query struct {
}

type User struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Age    *int   `json:"age,omitempty"`
	Active bool   `json:"active"`
}

type UserFilter struct {
	Name   graphql.Omittable[*string] `json:"name,omitempty"`
	Age    graphql.Omittable[*int]    `json:"age,omitempty"`
	Active graphql.Omittable[*bool]   `json:"active,omitempty"`
}
