// Code generated by github.com/gqlgo/gqlgenc, DO NOT EDIT.

package generated

import (
	"context"

	"github.com/gqlgo/gqlgenc/clientv2"
)

type Client struct {
	Client *clientv2.Client
}

func NewClient(cli clientv2.HttpClient, baseURL string, options *clientv2.Options, interceptors ...clientv2.RequestInterceptor) *Client {
	return &Client{Client: clientv2.NewClient(cli, baseURL, options, interceptors...)}
}

type CreateMany_CreateTodos_Todos struct {
	ID     string     "json:\"id\" graphql:\"id\""
	Status TodoStatus "json:\"status\" graphql:\"status\""
}

func (t *CreateMany_CreateTodos_Todos) GetID() string {
	if t == nil {
		t = &CreateMany_CreateTodos_Todos{}
	}
	return t.ID
}
func (t *CreateMany_CreateTodos_Todos) GetStatus() *TodoStatus {
	if t == nil {
		t = &CreateMany_CreateTodos_Todos{}
	}
	return &t.Status
}

type CreateMany_CreateTodos struct {
	Todos []*CreateMany_CreateTodos_Todos "json:\"todos\" graphql:\"todos\""
}

func (t *CreateMany_CreateTodos) GetTodos() []*CreateMany_CreateTodos_Todos {
	if t == nil {
		t = &CreateMany_CreateTodos{}
	}
	return t.Todos
}

type GetBySortOrder_TodosBySortOrder struct {
	ID string "json:\"id\" graphql:\"id\""
}

func (t *GetBySortOrder_TodosBySortOrder) GetID() string {
	if t == nil {
		t = &GetBySortOrder_TodosBySortOrder{}
	}
	return t.ID
}

type CreateMany struct {
	CreateTodos *CreateMany_CreateTodos "json:\"createTodos,omitempty\" graphql:\"createTodos\""
}

func (t *CreateMany) GetCreateTodos() *CreateMany_CreateTodos {
	if t == nil {
		t = &CreateMany{}
	}
	return t.CreateTodos
}

type GetBySortOrder struct {
	TodosBySortOrder []*GetBySortOrder_TodosBySortOrder "json:\"todosBySortOrder\" graphql:\"todosBySortOrder\""
}

func (t *GetBySortOrder) GetTodosBySortOrder() []*GetBySortOrder_TodosBySortOrder {
	if t == nil {
		t = &GetBySortOrder{}
	}
	return t.TodosBySortOrder
}

const CreateManyDocument = `mutation CreateMany ($todos: NewTodos!) {
	createTodos(input: $todos) {
		todos {
			id
			status
		}
	}
}
`

func (c *Client) CreateMany(ctx context.Context, todos NewTodos, interceptors ...clientv2.RequestInterceptor) (*CreateMany, error) {
	vars := map[string]any{
		"todos": todos,
	}

	var res CreateMany
	if err := c.Client.Post(ctx, "CreateMany", CreateManyDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const GetBySortOrderDocument = `query GetBySortOrder ($order: SortOrder!) {
	todosBySortOrder(order: $order) {
		id
	}
}
`

func (c *Client) GetBySortOrder(ctx context.Context, order SortOrder, interceptors ...clientv2.RequestInterceptor) (*GetBySortOrder, error) {
	vars := map[string]any{
		"order": order,
	}

	var res GetBySortOrder
	if err := c.Client.Post(ctx, "GetBySortOrder", GetBySortOrderDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

var DocumentOperationNames = map[string]string{
	CreateManyDocument:     "CreateMany",
	GetBySortOrderDocument: "GetBySortOrder",
}
