// Code generated by github.com/gqlgo/gqlgenc, DO NOT EDIT.

package generated

import (
	"context"

	"github.com/gqlgo/gqlgenc/clientv2"
)

type Client struct {
	Client *clientv2.Client
}

func NewClient(cli clientv2.HttpClient, baseURL string, options *clientv2.Options, interceptors ...clientv2.RequestInterceptor) *Client {
	return &Client{Client: clientv2.NewClient(cli, baseURL, options, interceptors...)}
}

type GetPost_Post_Author struct {
	ID   string "json:\"id\" graphql:\"id\""
	Name string "json:\"name\" graphql:\"name\""
}

func (t *GetPost_Post_Author) GetID() string {
	if t == nil {
		t = &GetPost_Post_Author{}
	}
	return t.ID
}
func (t *GetPost_Post_Author) GetName() string {
	if t == nil {
		t = &GetPost_Post_Author{}
	}
	return t.Name
}

type GetPost_Post struct {
	Author  GetPost_Post_Author "json:\"author\" graphql:\"author\""
	Content string              "json:\"content\" graphql:\"content\""
	ID      string              "json:\"id\" graphql:\"id\""
	Title   string              "json:\"title\" graphql:\"title\""
}

func (t *GetPost_Post) GetAuthor() *GetPost_Post_Author {
	if t == nil {
		t = &GetPost_Post{}
	}
	return &t.Author
}
func (t *GetPost_Post) GetContent() string {
	if t == nil {
		t = &GetPost_Post{}
	}
	return t.Content
}
func (t *GetPost_Post) GetID() string {
	if t == nil {
		t = &GetPost_Post{}
	}
	return t.ID
}
func (t *GetPost_Post) GetTitle() string {
	if t == nil {
		t = &GetPost_Post{}
	}
	return t.Title
}

type CreateUser_CreateUser struct {
	Email string "json:\"email\" graphql:\"email\""
	ID    string "json:\"id\" graphql:\"id\""
	Name  string "json:\"name\" graphql:\"name\""
}

func (t *CreateUser_CreateUser) GetEmail() string {
	if t == nil {
		t = &CreateUser_CreateUser{}
	}
	return t.Email
}
func (t *CreateUser_CreateUser) GetID() string {
	if t == nil {
		t = &CreateUser_CreateUser{}
	}
	return t.ID
}
func (t *CreateUser_CreateUser) GetName() string {
	if t == nil {
		t = &CreateUser_CreateUser{}
	}
	return t.Name
}

type UpdatePost_UpdatePost struct {
	Content string "json:\"content\" graphql:\"content\""
	ID      string "json:\"id\" graphql:\"id\""
	Title   string "json:\"title\" graphql:\"title\""
}

func (t *UpdatePost_UpdatePost) GetContent() string {
	if t == nil {
		t = &UpdatePost_UpdatePost{}
	}
	return t.Content
}
func (t *UpdatePost_UpdatePost) GetID() string {
	if t == nil {
		t = &UpdatePost_UpdatePost{}
	}
	return t.ID
}
func (t *UpdatePost_UpdatePost) GetTitle() string {
	if t == nil {
		t = &UpdatePost_UpdatePost{}
	}
	return t.Title
}

type GetUser_User_Posts struct {
	ID    string "json:\"id\" graphql:\"id\""
	Title string "json:\"title\" graphql:\"title\""
}

func (t *GetUser_User_Posts) GetID() string {
	if t == nil {
		t = &GetUser_User_Posts{}
	}
	return t.ID
}
func (t *GetUser_User_Posts) GetTitle() string {
	if t == nil {
		t = &GetUser_User_Posts{}
	}
	return t.Title
}

type GetUser_User struct {
	Email string                "json:\"email\" graphql:\"email\""
	ID    string                "json:\"id\" graphql:\"id\""
	Name  string                "json:\"name\" graphql:\"name\""
	Posts []*GetUser_User_Posts "json:\"posts\" graphql:\"posts\""
}

func (t *GetUser_User) GetEmail() string {
	if t == nil {
		t = &GetUser_User{}
	}
	return t.Email
}
func (t *GetUser_User) GetID() string {
	if t == nil {
		t = &GetUser_User{}
	}
	return t.ID
}
func (t *GetUser_User) GetName() string {
	if t == nil {
		t = &GetUser_User{}
	}
	return t.Name
}
func (t *GetUser_User) GetPosts() []*GetUser_User_Posts {
	if t == nil {
		t = &GetUser_User{}
	}
	return t.Posts
}

type ListUsers_Users struct {
	ID   string "json:\"id\" graphql:\"id\""
	Name string "json:\"name\" graphql:\"name\""
}

func (t *ListUsers_Users) GetID() string {
	if t == nil {
		t = &ListUsers_Users{}
	}
	return t.ID
}
func (t *ListUsers_Users) GetName() string {
	if t == nil {
		t = &ListUsers_Users{}
	}
	return t.Name
}

type GetPost struct {
	Post GetPost_Post "json:\"post\" graphql:\"post\""
}

func (t *GetPost) GetPost() *GetPost_Post {
	if t == nil {
		t = &GetPost{}
	}
	return &t.Post
}

type CreateUser struct {
	CreateUser CreateUser_CreateUser "json:\"createUser\" graphql:\"createUser\""
}

func (t *CreateUser) GetCreateUser() *CreateUser_CreateUser {
	if t == nil {
		t = &CreateUser{}
	}
	return &t.CreateUser
}

type UpdatePost struct {
	UpdatePost UpdatePost_UpdatePost "json:\"updatePost\" graphql:\"updatePost\""
}

func (t *UpdatePost) GetUpdatePost() *UpdatePost_UpdatePost {
	if t == nil {
		t = &UpdatePost{}
	}
	return &t.UpdatePost
}

type GetUser struct {
	User GetUser_User "json:\"user\" graphql:\"user\""
}

func (t *GetUser) GetUser() *GetUser_User {
	if t == nil {
		t = &GetUser{}
	}
	return &t.User
}

type ListUsers struct {
	Users []*ListUsers_Users "json:\"users\" graphql:\"users\""
}

func (t *ListUsers) GetUsers() []*ListUsers_Users {
	if t == nil {
		t = &ListUsers{}
	}
	return t.Users
}

const GetPostDocument = `query GetPost ($id: ID!) {
	post(id: $id) {
		id
		title
		content
		author {
			id
			name
		}
	}
}
`

func (c *Client) GetPost(ctx context.Context, id string, interceptors ...clientv2.RequestInterceptor) (*GetPost, error) {
	vars := map[string]any{
		"id": id,
	}

	var res GetPost
	if err := c.Client.Post(ctx, "GetPost", GetPostDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const CreateUserDocument = `mutation CreateUser ($input: CreateUserInput!) {
	createUser(input: $input) {
		id
		name
		email
	}
}
`

func (c *Client) CreateUser(ctx context.Context, input CreateUserInput, interceptors ...clientv2.RequestInterceptor) (*CreateUser, error) {
	vars := map[string]any{
		"input": input,
	}

	var res CreateUser
	if err := c.Client.Post(ctx, "CreateUser", CreateUserDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const UpdatePostDocument = `mutation UpdatePost ($id: ID!, $input: UpdatePostInput!) {
	updatePost(id: $id, input: $input) {
		id
		title
		content
	}
}
`

func (c *Client) UpdatePost(ctx context.Context, id string, input UpdatePostInput, interceptors ...clientv2.RequestInterceptor) (*UpdatePost, error) {
	vars := map[string]any{
		"id":    id,
		"input": input,
	}

	var res UpdatePost
	if err := c.Client.Post(ctx, "UpdatePost", UpdatePostDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const GetUserDocument = `query GetUser ($id: ID!) {
	user(id: $id) {
		id
		name
		email
		posts {
			id
			title
		}
	}
}
`

func (c *Client) GetUser(ctx context.Context, id string, interceptors ...clientv2.RequestInterceptor) (*GetUser, error) {
	vars := map[string]any{
		"id": id,
	}

	var res GetUser
	if err := c.Client.Post(ctx, "GetUser", GetUserDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const ListUsersDocument = `query ListUsers {
	users {
		id
		name
	}
}
`

func (c *Client) ListUsers(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*ListUsers, error) {
	vars := map[string]any{}

	var res ListUsers
	if err := c.Client.Post(ctx, "ListUsers", ListUsersDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

var DocumentOperationNames = map[string]string{
	GetPostDocument:    "GetPost",
	CreateUserDocument: "CreateUser",
	UpdatePostDocument: "UpdatePost",
	GetUserDocument:    "GetUser",
	ListUsersDocument:  "ListUsers",
}
