// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package generated

type CreateUserInput struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type Mutation struct {
}

type Post struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
	Author  *User  `json:"author"`
}

type Query struct {
}

type UpdatePostInput struct {
	Title   *string `json:"title,omitempty"`
	Content *string `json:"content,omitempty"`
}

type User struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Email string  `json:"email"`
	Posts []*Post `json:"posts"`
}
