// Code generated by github.com/gqlgo/gqlgenc, DO NOT EDIT.

package generated

import (
	"context"

	"github.com/gqlgo/gqlgenc/clientv2"
)

type Client struct {
	Client *clientv2.Client
}

func NewClient(cli clientv2.HttpClient, baseURL string, options *clientv2.Options, interceptors ...clientv2.RequestInterceptor) *Client {
	return &Client{Client: clientv2.NewClient(cli, baseURL, options, interceptors...)}
}

type Hello struct {
	Hello string "json:\"hello\" graphql:\"hello\""
}

func (t *Hello) GetHello() string {
	if t == nil {
		t = &Hello{}
	}
	return t.Hello
}

const HelloDocument = `query Hello {
	hello
}
`

func (c *Client) Hello(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*Hello, error) {
	vars := map[string]any{}

	var res Hello
	if err := c.Client.Post(ctx, "Hello", HelloDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

var DocumentOperationNames = map[string]string{
	HelloDocument: "Hello",
}
