// Code generated by github.com/gqlgo/gqlgenc, DO NOT EDIT.

package generated

import (
	"context"

	"github.com/gqlgo/gqlgenc/clientv2"
)

type Client struct {
	Client *clientv2.Client
}

func NewClient(cli clientv2.HttpClient, baseURL string, options *clientv2.Options, interceptors ...clientv2.RequestInterceptor) *Client {
	return &Client{Client: clientv2.NewClient(cli, baseURL, options, interceptors...)}
}

type NameFrag struct {
	Name string "json:\"name\" graphql:\"name\""
}

func (t *NameFrag) GetName() string {
	if t == nil {
		t = &NameFrag{}
	}
	return t.Name
}

type PersonBasic struct {
	NameFrag *NameFrag
	Address  string "json:\"address\" graphql:\"address\""
}

func (t *PersonBasic) GetNameFrag() *NameFrag {
	if t == nil {
		t = &PersonBasic{}
	}
	return t.NameFrag
}
func (t *PersonBasic) GetAddress() string {
	if t == nil {
		t = &PersonBasic{}
	}
	return t.Address
}

type ProfileBioFrag struct {
	Profile ProfileBioFrag_Profile "json:\"profile\" graphql:\"profile\""
}

func (t *ProfileBioFrag) GetProfile() *ProfileBioFrag_Profile {
	if t == nil {
		t = &ProfileBioFrag{}
	}
	return &t.Profile
}

type FullProfile struct {
	ProfileBioFrag *ProfileBioFrag
	Profile        FullProfile_Profile "json:\"profile\" graphql:\"profile\""
}

func (t *FullProfile) GetProfileBioFrag() *ProfileBioFrag {
	if t == nil {
		t = &FullProfile{}
	}
	return t.ProfileBioFrag
}
func (t *FullProfile) GetProfile() *FullProfile_Profile {
	if t == nil {
		t = &FullProfile{}
	}
	return &t.Profile
}

type FragC struct {
	Name string "json:\"name\" graphql:\"name\""
}

func (t *FragC) GetName() string {
	if t == nil {
		t = &FragC{}
	}
	return t.Name
}

type FragB struct {
	FragC   *FragC
	Address string "json:\"address\" graphql:\"address\""
}

func (t *FragB) GetFragC() *FragC {
	if t == nil {
		t = &FragB{}
	}
	return t.FragC
}
func (t *FragB) GetAddress() string {
	if t == nil {
		t = &FragB{}
	}
	return t.Address
}

type FragA struct {
	FragB *FragB
	Age   int "json:\"age\" graphql:\"age\""
}

func (t *FragA) GetFragB() *FragB {
	if t == nil {
		t = &FragA{}
	}
	return t.FragB
}
func (t *FragA) GetAge() int {
	if t == nil {
		t = &FragA{}
	}
	return t.Age
}

type ProfileBioFrag_Profile struct {
	Bio string "json:\"bio\" graphql:\"bio\""
}

func (t *ProfileBioFrag_Profile) GetBio() string {
	if t == nil {
		t = &ProfileBioFrag_Profile{}
	}
	return t.Bio
}

type FullProfile_ProfileBioFrag_Profile struct {
	Bio string "json:\"bio\" graphql:\"bio\""
}

func (t *FullProfile_ProfileBioFrag_Profile) GetBio() string {
	if t == nil {
		t = &FullProfile_ProfileBioFrag_Profile{}
	}
	return t.Bio
}

type FullProfile_Profile struct {
	Avatar string "json:\"avatar\" graphql:\"avatar\""
	Bio    string "json:\"bio\" graphql:\"bio\""
}

func (t *FullProfile_Profile) GetAvatar() string {
	if t == nil {
		t = &FullProfile_Profile{}
	}
	return t.Avatar
}
func (t *FullProfile_Profile) GetBio() string {
	if t == nil {
		t = &FullProfile_Profile{}
	}
	return t.Bio
}

type GetFullProfile_Person_FullProfile_ProfileBioFrag_Profile struct {
	Bio string "json:\"bio\" graphql:\"bio\""
}

func (t *GetFullProfile_Person_FullProfile_ProfileBioFrag_Profile) GetBio() string {
	if t == nil {
		t = &GetFullProfile_Person_FullProfile_ProfileBioFrag_Profile{}
	}
	return t.Bio
}

type GetFullProfile_Person_FullProfile_Profile struct {
	Avatar string "json:\"avatar\" graphql:\"avatar\""
	Bio    string "json:\"bio\" graphql:\"bio\""
}

func (t *GetFullProfile_Person_FullProfile_Profile) GetAvatar() string {
	if t == nil {
		t = &GetFullProfile_Person_FullProfile_Profile{}
	}
	return t.Avatar
}
func (t *GetFullProfile_Person_FullProfile_Profile) GetBio() string {
	if t == nil {
		t = &GetFullProfile_Person_FullProfile_Profile{}
	}
	return t.Bio
}

type GetPersonBasic struct {
	Person *PersonBasic "json:\"person\" graphql:\"person\""
}

func (t *GetPersonBasic) GetPerson() *PersonBasic {
	if t == nil {
		t = &GetPersonBasic{}
	}
	return t.Person
}

type GetFullProfile struct {
	Person *FullProfile "json:\"person\" graphql:\"person\""
}

func (t *GetFullProfile) GetPerson() *FullProfile {
	if t == nil {
		t = &GetFullProfile{}
	}
	return t.Person
}

type GetFragA struct {
	Person *FragA "json:\"person\" graphql:\"person\""
}

func (t *GetFragA) GetPerson() *FragA {
	if t == nil {
		t = &GetFragA{}
	}
	return t.Person
}

const GetPersonBasicDocument = `query GetPersonBasic {
	person {
		... PersonBasic
	}
}
fragment PersonBasic on Person {
	... NameFrag
	address
}
fragment NameFrag on Person {
	name
}
`

func (c *Client) GetPersonBasic(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*GetPersonBasic, error) {
	vars := map[string]any{}

	var res GetPersonBasic
	if err := c.Client.Post(ctx, "GetPersonBasic", GetPersonBasicDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const GetFullProfileDocument = `query GetFullProfile {
	person {
		... FullProfile
	}
}
fragment FullProfile on Person {
	... ProfileBioFrag
	profile {
		bio
		avatar
	}
}
fragment ProfileBioFrag on Person {
	profile {
		bio
	}
}
`

func (c *Client) GetFullProfile(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*GetFullProfile, error) {
	vars := map[string]any{}

	var res GetFullProfile
	if err := c.Client.Post(ctx, "GetFullProfile", GetFullProfileDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const GetFragADocument = `query GetFragA {
	person {
		... FragA
	}
}
fragment FragA on Person {
	... FragB
	age
}
fragment FragB on Person {
	... FragC
	address
}
fragment FragC on Person {
	name
}
`

func (c *Client) GetFragA(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*GetFragA, error) {
	vars := map[string]any{}

	var res GetFragA
	if err := c.Client.Post(ctx, "GetFragA", GetFragADocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

var DocumentOperationNames = map[string]string{
	GetPersonBasicDocument: "GetPersonBasic",
	GetFullProfileDocument: "GetFullProfile",
	GetFragADocument:       "GetFragA",
}
