// Code generated by github.com/gqlgo/gqlgenc, DO NOT EDIT.

package generated

import (
	"context"

	"github.com/gqlgo/gqlgenc/clientv2"
)

type Client struct {
	Client *clientv2.Client
}

func NewClient(cli clientv2.HttpClient, baseURL string, options *clientv2.Options, interceptors ...clientv2.RequestInterceptor) *Client {
	return &Client{Client: clientv2.NewClient(cli, baseURL, options, interceptors...)}
}

type NameFrag struct {
	Name string "json:\"name\" graphql:\"name\""
}

func (t *NameFrag) GetName() string {
	if t == nil {
		t = &NameFrag{}
	}
	return t.Name
}

type PersonBasic struct {
	Address string "json:\"address\" graphql:\"address\""
	Name    string "json:\"name\" graphql:\"name\""
}

func (t *PersonBasic) GetAddress() string {
	if t == nil {
		t = &PersonBasic{}
	}
	return t.Address
}
func (t *PersonBasic) GetName() string {
	if t == nil {
		t = &PersonBasic{}
	}
	return t.Name
}

func (t *PersonBasic) GetNameFrag() *NameFrag {
	if t == nil {
		t = &PersonBasic{}
	}
	return &NameFrag{
		Name: t.Name,
	}
}

type ProfileBioFrag struct {
	Profile ProfileBioFrag_Profile "json:\"profile\" graphql:\"profile\""
}

func (t *ProfileBioFrag) GetProfile() *ProfileBioFrag_Profile {
	if t == nil {
		t = &ProfileBioFrag{}
	}
	return &t.Profile
}

type FullProfile struct {
	Profile FullProfile_Profile "json:\"profile\" graphql:\"profile\""
}

func (t *FullProfile) GetProfile() *FullProfile_Profile {
	if t == nil {
		t = &FullProfile{}
	}
	return &t.Profile
}

func (t *FullProfile) GetProfileBioFrag() *ProfileBioFrag {
	if t == nil {
		t = &FullProfile{}
	}
	return &ProfileBioFrag{
		Profile: ProfileBioFrag_Profile{
			Bio: t.Profile.Bio,
		},
	}
}

type FragC struct {
	Name string "json:\"name\" graphql:\"name\""
}

func (t *FragC) GetName() string {
	if t == nil {
		t = &FragC{}
	}
	return t.Name
}

type FragB struct {
	Address string "json:\"address\" graphql:\"address\""
	Name    string "json:\"name\" graphql:\"name\""
}

func (t *FragB) GetAddress() string {
	if t == nil {
		t = &FragB{}
	}
	return t.Address
}
func (t *FragB) GetName() string {
	if t == nil {
		t = &FragB{}
	}
	return t.Name
}

func (t *FragB) GetFragC() *FragC {
	if t == nil {
		t = &FragB{}
	}
	return &FragC{
		Name: t.Name,
	}
}

type FragA struct {
	Address string "json:\"address\" graphql:\"address\""
	Age     int    "json:\"age\" graphql:\"age\""
	Name    string "json:\"name\" graphql:\"name\""
}

func (t *FragA) GetAddress() string {
	if t == nil {
		t = &FragA{}
	}
	return t.Address
}
func (t *FragA) GetAge() int {
	if t == nil {
		t = &FragA{}
	}
	return t.Age
}
func (t *FragA) GetName() string {
	if t == nil {
		t = &FragA{}
	}
	return t.Name
}

func (t *FragA) GetFragB() *FragB {
	if t == nil {
		t = &FragA{}
	}
	return &FragB{
		Address: t.Address,
		Name:    t.Name,
	}
}

type AgeFrag struct {
	Age int "json:\"age\" graphql:\"age\""
}

func (t *AgeFrag) GetAge() int {
	if t == nil {
		t = &AgeFrag{}
	}
	return t.Age
}

type NameAgeFrag struct {
	Name string "json:\"name\" graphql:\"name\""
	Age  int    "json:\"age\" graphql:\"age\""
}

func (t *NameAgeFrag) GetName() string {
	if t == nil {
		t = &NameAgeFrag{}
	}
	return t.Name
}
func (t *NameAgeFrag) GetAge() int {
	if t == nil {
		t = &NameAgeFrag{}
	}
	return t.Age
}

type MultiSpreadOverlap struct {
	Address string "json:\"address\" graphql:\"address\""
	Age     int    "json:\"age\" graphql:\"age\""
	Name    string "json:\"name\" graphql:\"name\""
}

func (t *MultiSpreadOverlap) GetAddress() string {
	if t == nil {
		t = &MultiSpreadOverlap{}
	}
	return t.Address
}
func (t *MultiSpreadOverlap) GetAge() int {
	if t == nil {
		t = &MultiSpreadOverlap{}
	}
	return t.Age
}
func (t *MultiSpreadOverlap) GetName() string {
	if t == nil {
		t = &MultiSpreadOverlap{}
	}
	return t.Name
}

func (t *MultiSpreadOverlap) GetAgeFrag() *AgeFrag {
	if t == nil {
		t = &MultiSpreadOverlap{}
	}
	return &AgeFrag{
		Age: t.Age,
	}
}
func (t *MultiSpreadOverlap) GetNameAgeFrag() *NameAgeFrag {
	if t == nil {
		t = &MultiSpreadOverlap{}
	}
	return &NameAgeFrag{
		Name: t.Name,
		Age:  t.Age,
	}
}

type DirectOverlap struct {
	Age  int    "json:\"age\" graphql:\"age\""
	Name string "json:\"name\" graphql:\"name\""
}

func (t *DirectOverlap) GetAge() int {
	if t == nil {
		t = &DirectOverlap{}
	}
	return t.Age
}
func (t *DirectOverlap) GetName() string {
	if t == nil {
		t = &DirectOverlap{}
	}
	return t.Name
}

func (t *DirectOverlap) GetNameFrag() *NameFrag {
	if t == nil {
		t = &DirectOverlap{}
	}
	return &NameFrag{
		Name: t.Name,
	}
}

type NicknameFrag struct {
	Nickname *string "json:\"nickname,omitempty\" graphql:\"nickname\""
}

func (t *NicknameFrag) GetNickname() *string {
	if t == nil {
		t = &NicknameFrag{}
	}
	return t.Nickname
}

type PersonWithNickname struct {
	Name     string  "json:\"name\" graphql:\"name\""
	Nickname *string "json:\"nickname,omitempty\" graphql:\"nickname\""
}

func (t *PersonWithNickname) GetName() string {
	if t == nil {
		t = &PersonWithNickname{}
	}
	return t.Name
}
func (t *PersonWithNickname) GetNickname() *string {
	if t == nil {
		t = &PersonWithNickname{}
	}
	return t.Nickname
}

func (t *PersonWithNickname) GetNicknameFrag() *NicknameFrag {
	if t == nil {
		t = &PersonWithNickname{}
	}
	return &NicknameFrag{
		Nickname: t.Nickname,
	}
}

type ProfileBioFrag_Profile struct {
	Bio string "json:\"bio\" graphql:\"bio\""
}

func (t *ProfileBioFrag_Profile) GetBio() string {
	if t == nil {
		t = &ProfileBioFrag_Profile{}
	}
	return t.Bio
}

type FullProfile_ProfileBioFrag_Profile struct {
	Bio string "json:\"bio\" graphql:\"bio\""
}

func (t *FullProfile_ProfileBioFrag_Profile) GetBio() string {
	if t == nil {
		t = &FullProfile_ProfileBioFrag_Profile{}
	}
	return t.Bio
}

type FullProfile_Profile struct {
	Avatar string "json:\"avatar\" graphql:\"avatar\""
	Bio    string "json:\"bio\" graphql:\"bio\""
}

func (t *FullProfile_Profile) GetAvatar() string {
	if t == nil {
		t = &FullProfile_Profile{}
	}
	return t.Avatar
}
func (t *FullProfile_Profile) GetBio() string {
	if t == nil {
		t = &FullProfile_Profile{}
	}
	return t.Bio
}

type GetFullProfile_Person_FullProfile_ProfileBioFrag_Profile struct {
	Bio string "json:\"bio\" graphql:\"bio\""
}

func (t *GetFullProfile_Person_FullProfile_ProfileBioFrag_Profile) GetBio() string {
	if t == nil {
		t = &GetFullProfile_Person_FullProfile_ProfileBioFrag_Profile{}
	}
	return t.Bio
}

type GetFullProfile_Person_FullProfile_Profile struct {
	Avatar string "json:\"avatar\" graphql:\"avatar\""
	Bio    string "json:\"bio\" graphql:\"bio\""
}

func (t *GetFullProfile_Person_FullProfile_Profile) GetAvatar() string {
	if t == nil {
		t = &GetFullProfile_Person_FullProfile_Profile{}
	}
	return t.Avatar
}
func (t *GetFullProfile_Person_FullProfile_Profile) GetBio() string {
	if t == nil {
		t = &GetFullProfile_Person_FullProfile_Profile{}
	}
	return t.Bio
}

type GetPersonDirect_Person struct {
	Address string "json:\"address\" graphql:\"address\""
	Age     int    "json:\"age\" graphql:\"age\""
	Name    string "json:\"name\" graphql:\"name\""
}

func (t *GetPersonDirect_Person) GetAddress() string {
	if t == nil {
		t = &GetPersonDirect_Person{}
	}
	return t.Address
}
func (t *GetPersonDirect_Person) GetAge() int {
	if t == nil {
		t = &GetPersonDirect_Person{}
	}
	return t.Age
}
func (t *GetPersonDirect_Person) GetName() string {
	if t == nil {
		t = &GetPersonDirect_Person{}
	}
	return t.Name
}

type GetPersonBasic struct {
	Person *PersonBasic "json:\"person\" graphql:\"person\""
}

func (t *GetPersonBasic) GetPerson() *PersonBasic {
	if t == nil {
		t = &GetPersonBasic{}
	}
	return t.Person
}

type GetFullProfile struct {
	Person *FullProfile "json:\"person\" graphql:\"person\""
}

func (t *GetFullProfile) GetPerson() *FullProfile {
	if t == nil {
		t = &GetFullProfile{}
	}
	return t.Person
}

type GetFragA struct {
	Person *FragA "json:\"person\" graphql:\"person\""
}

func (t *GetFragA) GetPerson() *FragA {
	if t == nil {
		t = &GetFragA{}
	}
	return t.Person
}

type GetMultiSpreadOverlap struct {
	Person *MultiSpreadOverlap "json:\"person\" graphql:\"person\""
}

func (t *GetMultiSpreadOverlap) GetPerson() *MultiSpreadOverlap {
	if t == nil {
		t = &GetMultiSpreadOverlap{}
	}
	return t.Person
}

type GetDirectOverlap struct {
	Person *DirectOverlap "json:\"person\" graphql:\"person\""
}

func (t *GetDirectOverlap) GetPerson() *DirectOverlap {
	if t == nil {
		t = &GetDirectOverlap{}
	}
	return t.Person
}

type GetPersonWithNickname struct {
	Person *PersonWithNickname "json:\"person\" graphql:\"person\""
}

func (t *GetPersonWithNickname) GetPerson() *PersonWithNickname {
	if t == nil {
		t = &GetPersonWithNickname{}
	}
	return t.Person
}

type GetPersonDirect struct {
	Person GetPersonDirect_Person "json:\"person\" graphql:\"person\""
}

func (t *GetPersonDirect) GetPerson() *GetPersonDirect_Person {
	if t == nil {
		t = &GetPersonDirect{}
	}
	return &t.Person
}

type GetPeople struct {
	People []*PersonBasic "json:\"people\" graphql:\"people\""
}

func (t *GetPeople) GetPeople() []*PersonBasic {
	if t == nil {
		t = &GetPeople{}
	}
	return t.People
}

const GetPersonBasicDocument = `query GetPersonBasic {
	person {
		... PersonBasic
	}
}
fragment PersonBasic on Person {
	... NameFrag
	address @dummy_custom(value: "742 Evergreen Terrace")
}
fragment NameFrag on Person {
	name @dummy_custom(value: "Homer Simpson")
}
`

func (c *Client) GetPersonBasic(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*GetPersonBasic, error) {
	vars := map[string]any{}

	var res GetPersonBasic
	if err := c.Client.Post(ctx, "GetPersonBasic", GetPersonBasicDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const GetFullProfileDocument = `query GetFullProfile {
	person {
		... FullProfile
	}
}
fragment FullProfile on Person {
	... ProfileBioFrag
	profile {
		bio @dummy_custom(value: "Nuclear safety inspector")
		avatar @dummy_custom(value: "https://example.com/homer.png")
	}
}
fragment ProfileBioFrag on Person {
	profile {
		bio @dummy_custom(value: "Nuclear safety inspector")
	}
}
`

func (c *Client) GetFullProfile(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*GetFullProfile, error) {
	vars := map[string]any{}

	var res GetFullProfile
	if err := c.Client.Post(ctx, "GetFullProfile", GetFullProfileDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const GetFragADocument = `query GetFragA {
	person {
		... FragA
	}
}
fragment FragA on Person {
	... FragB
	age @dummy_int(min: 39, max: 39)
}
fragment FragB on Person {
	... FragC
	address @dummy_custom(value: "742 Evergreen Terrace")
}
fragment FragC on Person {
	name @dummy_custom(value: "Homer Simpson")
}
`

func (c *Client) GetFragA(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*GetFragA, error) {
	vars := map[string]any{}

	var res GetFragA
	if err := c.Client.Post(ctx, "GetFragA", GetFragADocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const GetMultiSpreadOverlapDocument = `query GetMultiSpreadOverlap {
	person {
		... MultiSpreadOverlap
	}
}
fragment MultiSpreadOverlap on Person {
	... AgeFrag
	... NameAgeFrag
	address @dummy_custom(value: "Springfield")
}
fragment AgeFrag on Person {
	age @dummy_int(min: 39, max: 39)
}
fragment NameAgeFrag on Person {
	name @dummy_custom(value: "Homer")
	age @dummy_int(min: 39, max: 39)
}
`

func (c *Client) GetMultiSpreadOverlap(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*GetMultiSpreadOverlap, error) {
	vars := map[string]any{}

	var res GetMultiSpreadOverlap
	if err := c.Client.Post(ctx, "GetMultiSpreadOverlap", GetMultiSpreadOverlapDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const GetDirectOverlapDocument = `query GetDirectOverlap {
	person {
		... DirectOverlap
	}
}
fragment DirectOverlap on Person {
	... NameFrag
	name @dummy_custom(value: "Homer Simpson")
	age @dummy_int(min: 10, max: 10)
}
fragment NameFrag on Person {
	name @dummy_custom(value: "Homer Simpson")
}
`

func (c *Client) GetDirectOverlap(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*GetDirectOverlap, error) {
	vars := map[string]any{}

	var res GetDirectOverlap
	if err := c.Client.Post(ctx, "GetDirectOverlap", GetDirectOverlapDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const GetPersonWithNicknameDocument = `query GetPersonWithNickname {
	person {
		... PersonWithNickname
	}
}
fragment PersonWithNickname on Person {
	... NicknameFrag
	name @dummy_custom(value: "Homer Simpson")
}
fragment NicknameFrag on Person {
	nickname @dummy_custom(value: "Homie")
}
`

func (c *Client) GetPersonWithNickname(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*GetPersonWithNickname, error) {
	vars := map[string]any{}

	var res GetPersonWithNickname
	if err := c.Client.Post(ctx, "GetPersonWithNickname", GetPersonWithNicknameDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const GetPersonDirectDocument = `query GetPersonDirect {
	person {
		name @dummy_custom(value: "Marge Simpson")
		address @dummy_custom(value: "742 Evergreen Terrace")
		age @dummy_int(min: 36, max: 36)
	}
}
`

func (c *Client) GetPersonDirect(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*GetPersonDirect, error) {
	vars := map[string]any{}

	var res GetPersonDirect
	if err := c.Client.Post(ctx, "GetPersonDirect", GetPersonDirectDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const GetPeopleDocument = `query GetPeople ($limit: Int!) {
	people(limit: $limit) @dummy_list_size(size: 2) {
		... PersonBasic
	}
}
fragment PersonBasic on Person {
	... NameFrag
	address @dummy_custom(value: "742 Evergreen Terrace")
}
fragment NameFrag on Person {
	name @dummy_custom(value: "Homer Simpson")
}
`

func (c *Client) GetPeople(ctx context.Context, limit int, interceptors ...clientv2.RequestInterceptor) (*GetPeople, error) {
	vars := map[string]any{
		"limit": limit,
	}

	var res GetPeople
	if err := c.Client.Post(ctx, "GetPeople", GetPeopleDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

var DocumentOperationNames = map[string]string{
	GetPersonBasicDocument:        "GetPersonBasic",
	GetFullProfileDocument:        "GetFullProfile",
	GetFragADocument:              "GetFragA",
	GetMultiSpreadOverlapDocument: "GetMultiSpreadOverlap",
	GetDirectOverlapDocument:      "GetDirectOverlap",
	GetPersonWithNicknameDocument: "GetPersonWithNickname",
	GetPersonDirectDocument:       "GetPersonDirect",
	GetPeopleDocument:             "GetPeople",
}
