// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package generated

type Person struct {
	Name     string   `json:"name"`
	Address  string   `json:"address"`
	Age      int      `json:"age"`
	Nickname *string  `json:"nickname,omitempty"`
	Profile  *Profile `json:"profile"`
}

type Profile struct {
	Bio     string `json:"bio"`
	Avatar  string `json:"avatar"`
	Website string `json:"website"`
}

type Query struct {
}
