// Code generated by github.com/gqlgo/gqlgenc, DO NOT EDIT.

package generated

import (
	"context"

	"github.com/gqlgo/gqlgenc/clientv2"
)

type Client struct {
	Client *clientv2.Client
}

func NewClient(cli clientv2.HttpClient, baseURL string, options *clientv2.Options, interceptors ...clientv2.RequestInterceptor) *Client {
	return &Client{Client: clientv2.NewClient(cli, baseURL, options, interceptors...)}
}

type Paint_Paint struct {
	ID    string   "json:\"id\" graphql:\"id\""
	Tones [][]Tone "json:\"tones\" graphql:\"tones\""
}

func (t *Paint_Paint) GetID() string {
	if t == nil {
		t = &Paint_Paint{}
	}
	return t.ID
}
func (t *Paint_Paint) GetTones() [][]Tone {
	if t == nil {
		t = &Paint_Paint{}
	}
	return t.Tones
}

type Paint struct {
	Paint *Paint_Paint "json:\"paint,omitempty\" graphql:\"paint\""
}

func (t *Paint) GetPaint() *Paint_Paint {
	if t == nil {
		t = &Paint{}
	}
	return t.Paint
}

const PaintDocument = `mutation Paint ($input: PaintInput!) {
	paint(input: $input) {
		id
		tones
	}
}
`

func (c *Client) Paint(ctx context.Context, input PaintInput, interceptors ...clientv2.RequestInterceptor) (*Paint, error) {
	vars := map[string]any{
		"input": input,
	}

	var res Paint
	if err := c.Client.Post(ctx, "Paint", PaintDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

var DocumentOperationNames = map[string]string{
	PaintDocument: "Paint",
}
