// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package generated

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Cell struct {
	Shade    *Shade    `json:"shade,omitempty"`
	Children [][]*Cell `json:"children,omitempty"`
}

type PaintInput struct {
	Colors [][]Color `json:"colors"`
	Grid   [][]*Cell `json:"grid,omitempty"`
}

type Color string

const (
	ColorRed   Color = "RED"
	ColorGreen Color = "GREEN"
	ColorBlue  Color = "BLUE"
)

var AllColor = []Color{
	ColorRed,
	ColorGreen,
	ColorBlue,
}

func (e Color) IsValid() bool {
	switch e {
	case ColorRed, ColorGreen, ColorBlue:
		return true
	}
	return false
}

func (e Color) String() string {
	return string(e)
}

func (e *Color) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Color(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Color", str)
	}
	return nil
}

func (e Color) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Color) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Color) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Shade string

const (
	ShadeLight Shade = "LIGHT"
	ShadeDark  Shade = "DARK"
)

var AllShade = []Shade{
	ShadeLight,
	ShadeDark,
}

func (e Shade) IsValid() bool {
	switch e {
	case ShadeLight, ShadeDark:
		return true
	}
	return false
}

func (e Shade) String() string {
	return string(e)
}

func (e *Shade) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Shade(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Shade", str)
	}
	return nil
}

func (e Shade) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Shade) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Shade) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Tone string

const (
	ToneWarm Tone = "WARM"
	ToneCool Tone = "COOL"
)

var AllTone = []Tone{
	ToneWarm,
	ToneCool,
}

func (e Tone) IsValid() bool {
	switch e {
	case ToneWarm, ToneCool:
		return true
	}
	return false
}

func (e Tone) String() string {
	return string(e)
}

func (e *Tone) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Tone(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Tone", str)
	}
	return nil
}

func (e Tone) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Tone) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Tone) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
