package schema

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"fmt"

	"github.com/Yamashou/gqlgenc/v3/testdata/integration/basic/domain"
)

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, input *domain.UpdateUserInput) (*domain.UpdateUserPayload, error) {
	var name string
	if n, ok := input.Name.ValueOK(); ok {
		if n == nil {
			name = "nil"
		} else {
			name = *n
		}
	} else {
		name = "undefined"
	}

	var settings *domain.UserSettings
	if s, ok := input.Settings.ValueOK(); ok {
		if s == nil {
			settings = nil
		} else {
			settings = &domain.UserSettings{
				Theme:         s.Theme,
				Notifications: s.Notifications,
			}
		}
	}

	user := &domain.User{
		ID:       input.ID,
		Name:     name,
		Settings: settings,
	}
	return &domain.UpdateUserPayload{
		User: user,
	}, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context) (*domain.User, error) {
	return &domain.User{
		ID:   "1",
		Name: "John Doe",
	}, nil
}

// OptionalUser is the resolver for the optionalUser field.
func (r *queryResolver) OptionalUser(ctx context.Context) (*domain.User, error) {
	return &domain.User{
		ID:   "2",
		Name: "Sam Smith",
	}, nil
}

// Article is the resolver for the article field.
func (r *queryResolver) Article(ctx context.Context, id string) (*domain.Article, error) {
	rating := 4.5
	optionalRating := 3.8
	str1 := "element1"
	str2 := "element2"
	str3 := "nullable1"

	return &domain.Article{
		ID:           id,
		Title:        "Test Article",
		Tags:         []string{"tag1", "tag2", "tag3"},
		OptionalTags: []string{"optional1", "optional2"},
		Comments: []*domain.Comment{
			{ID: "1", Text: "First comment"},
			{ID: "2", Text: "Second comment"},
		},
		OptionalComments: []*domain.Comment{
			{ID: "3", Text: "Optional comment"},
		},
		Rating:               rating,
		OptionalRating:       &optionalRating,
		NullableElementsList: []*string{&str1, nil, &str2},
		FullyNullableList:    []*string{&str3, nil},
		Statuses:             []domain.Status{domain.StatusActive, domain.StatusInactive},
		OptionalStatuses:     []domain.Status{domain.StatusActive},
		Addresses: []domain.Address{
			&domain.PublicAddress{ID: "addr1", Street: "Public St", Public: true},
			&domain.PrivateAddress{ID: "addr2", Street: "Private St", Private: true},
		},
		OptionalAddresses: []domain.Address{
			&domain.PublicAddress{ID: "addr3", Street: "Optional St", Public: false},
		},
		Profiles: []domain.Profile{
			&domain.PublicProfile{ID: "prof1", Status: domain.StatusActive},
			&domain.PrivateProfile{ID: "prof2", Age: func() *int { i := 25; return &i }()},
		},
		OptionalProfiles: []domain.Profile{
			&domain.PublicProfile{ID: "prof3", Status: domain.StatusInactive},
		},
		Matrix: [][]string{
			{"a", "b", "c"},
			{"d", "e", "f"},
		},
		OptionalMatrix: [][]string{
			{"x", "y"},
		},
	}, nil
}

// Metadata is the resolver for the metadata field.
func (r *queryResolver) Metadata(ctx context.Context, id string) (*domain.Metadata, error) {
	data := `{"key":"value","number":123}`
	return &domain.Metadata{
		ID:   id,
		Data: &data,
	}, nil
}

// Profile is the resolver for the profile field.
func (r *userResolver) Profile(ctx context.Context, obj *domain.User) (domain.Profile, error) {
	age := 30
	return &domain.PrivateProfile{
		ID:  "profile1",
		Age: &age,
	}, nil
}

// OptionalProfile is the resolver for the optionalProfile field.
func (r *userResolver) OptionalProfile(ctx context.Context, obj *domain.User) (domain.Profile, error) {
	return &domain.PublicProfile{
		ID:     "profile2",
		Status: domain.StatusActive,
	}, nil
}

// Address is the resolver for the address field.
func (r *userResolver) Address(ctx context.Context, obj *domain.User) (domain.Address, error) {
	return &domain.PrivateAddress{
		ID:     "addr1",
		Street: "123 Main St",
	}, nil
}

// OptionalAddress is the resolver for the optionalAddress field.
func (r *userResolver) OptionalAddress(ctx context.Context, obj *domain.User) (domain.Address, error) {
	return &domain.PublicAddress{
		ID:     "addr2",
		Street: "456 Elm St",
	}, nil
}

// ProfilePic is the resolver for the profilePic field.
func (r *userResolver) ProfilePic(ctx context.Context, obj *domain.User, size int) (string, error) {
	return fmt.Sprintf("https://example.com/pic_%s_%d.jpg", obj.ID, size), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
