// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package domain

type Object struct {
	FooBar *string `json:"foo_bar,omitempty,omitzero"`
	FooBar *string `json:"fooBar,omitempty,omitzero"`
}

type Query struct {
}
