// Code generated by github.com/Yamashou/gqlgenc, DO NOT EDIT.

package query

import (
	"github.com/Yamashou/gqlgenc/v3/client"
	"github.com/Yamashou/gqlgenc/v3/testdata/integration/modelgen/domain"
)

type SearchVars struct {
	Input  domain.SearchInput  `json:"input"`
	Filter domain.SearchFilter `json:"filter"`
}

var SearchOp = client.Operation[client.Query, SearchVars, domain.Search]{
	Name:     "Search",
	Document: domain.SearchDocument,
}
