// Code generated by github.com/gqlgo/gqlgenc, DO NOT EDIT.

package generated

import (
	"context"

	"github.com/gqlgo/gqlgenc/clientv2"
)

type Client struct {
	Client *clientv2.Client
}

func NewClient(cli clientv2.HttpClient, baseURL string, options *clientv2.Options, interceptors ...clientv2.RequestInterceptor) *Client {
	return &Client{Client: clientv2.NewClient(cli, baseURL, options, interceptors...)}
}

type GetUser_User struct {
	Email *string "json:\"email,omitempty\" graphql:\"email\""
	ID    string  "json:\"id\" graphql:\"id\""
	Name  string  "json:\"name\" graphql:\"name\""
}

func (t *GetUser_User) GetEmail() *string {
	if t == nil {
		t = &GetUser_User{}
	}
	return t.Email
}
func (t *GetUser_User) GetID() string {
	if t == nil {
		t = &GetUser_User{}
	}
	return t.ID
}
func (t *GetUser_User) GetName() string {
	if t == nil {
		t = &GetUser_User{}
	}
	return t.Name
}

type ListUsers_Users struct {
	ID   string "json:\"id\" graphql:\"id\""
	Name string "json:\"name\" graphql:\"name\""
}

func (t *ListUsers_Users) GetID() string {
	if t == nil {
		t = &ListUsers_Users{}
	}
	return t.ID
}
func (t *ListUsers_Users) GetName() string {
	if t == nil {
		t = &ListUsers_Users{}
	}
	return t.Name
}

type CreateUser_CreateUser struct {
	ID   string "json:\"id\" graphql:\"id\""
	Name string "json:\"name\" graphql:\"name\""
}

func (t *CreateUser_CreateUser) GetID() string {
	if t == nil {
		t = &CreateUser_CreateUser{}
	}
	return t.ID
}
func (t *CreateUser_CreateUser) GetName() string {
	if t == nil {
		t = &CreateUser_CreateUser{}
	}
	return t.Name
}

type GqlGetUserResult struct {
	User GetUser_User "json:\"user\" graphql:\"user\""
}

func (t *GqlGetUserResult) GetUser() *GetUser_User {
	if t == nil {
		t = &GqlGetUserResult{}
	}
	return &t.User
}

type GqlListUsersResult struct {
	Users []*ListUsers_Users "json:\"users\" graphql:\"users\""
}

func (t *GqlListUsersResult) GetUsers() []*ListUsers_Users {
	if t == nil {
		t = &GqlListUsersResult{}
	}
	return t.Users
}

type GqlMutCreateUserResponse struct {
	CreateUser CreateUser_CreateUser "json:\"createUser\" graphql:\"createUser\""
}

func (t *GqlMutCreateUserResponse) GetCreateUser() *CreateUser_CreateUser {
	if t == nil {
		t = &GqlMutCreateUserResponse{}
	}
	return &t.CreateUser
}

const GetUserDocument = `query GetUser ($id: ID!) {
	user(id: $id) {
		id
		name
		email
	}
}
`

func (c *Client) GetUser(ctx context.Context, id string, interceptors ...clientv2.RequestInterceptor) (*GqlGetUserResult, error) {
	vars := map[string]any{
		"id": id,
	}

	var res GqlGetUserResult
	if err := c.Client.Post(ctx, "GetUser", GetUserDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const ListUsersDocument = `query ListUsers {
	users {
		id
		name
	}
}
`

func (c *Client) ListUsers(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*GqlListUsersResult, error) {
	vars := map[string]any{}

	var res GqlListUsersResult
	if err := c.Client.Post(ctx, "ListUsers", ListUsersDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const CreateUserDocument = `mutation CreateUser ($name: String!) {
	createUser(name: $name) {
		id
		name
	}
}
`

func (c *Client) CreateUser(ctx context.Context, name string, interceptors ...clientv2.RequestInterceptor) (*GqlMutCreateUserResponse, error) {
	vars := map[string]any{
		"name": name,
	}

	var res GqlMutCreateUserResponse
	if err := c.Client.Post(ctx, "CreateUser", CreateUserDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

var DocumentOperationNames = map[string]string{
	GetUserDocument:    "GetUser",
	ListUsersDocument:  "ListUsers",
	CreateUserDocument: "CreateUser",
}
